/**
 * 可选产物契约断言 + 入库生成物可复现性守卫（TS-20）。
 *
 * 背景：`docs/contracts/codegen-v1.md` 把三个产物声明为
 * 「由 `generateTypes()` 之外的工具写出」，但**只有文档、没有任何断言**：
 *
 * | 产物 | 写入者 | 此前的唯一覆盖 |
 * | --- | --- | --- |
 * | `.ubean/typed-router.d.ts` | `@ubean/vue` Vite 插件（两个写入器） | 无 |
 * | `.ubean/openapi.d.ts` | `generateOpenApiTypesFromServer()` | 只断 `export type paths` 一个词 |
 * | `benchmarks/bundle-baseline.json` | `ubean analyze` | 无（`analyze-lib` 单测只造内存对象） |
 *
 * 于是「写入器悄悄改了输出形状、文档没跟上」这类回归完全不可见 —— 下游消费者
 * （vue-router 的类型增强、typed client、体积门禁）拿到形状不对的文件时不会报错，
 * 只是静默失效。
 *
 * 为什么**不**照 SvelteKit `prepublishOnly` 那样做「重新生成 → `git diff --exit-code`」：
 * `.gitignore` 忽略 `.ubean`，全仓**唯一入库的生成物**只有 file-mode 示例的
 * `examples/routing-file-mode/src/router/_generated/{routes.ts,imports.ts}`，而
 * `.ubean/typed-router.d.ts` 有**两个**写入器（`packages/builder/src/vite.ts` 的
 * `@ubean/vue/generator` 与 `packages/vue/src/vite.ts` 的 `generateTypedRouter`，
 * 后者头部是 `// Generated by @ubean/vue — do not edit.`）。对未入库文件做 diff 守卫
 * 没有意义，所以这里改成：
 *
 * 1. **可复现性守卫**：对入库的两个 file-mode 生成物，用扫描器 + 生成器重新生成一遍，
 *    与磁盘上入库的字节**逐字节比对**。手工编辑生成物、或生成器改了却没重新生成，
 *    都会红（这就是「产物过期时守卫红」）。
 * 2. **契约断言**：对三个可选产物各断言「形状 + 关键字段」，让写入器的输出契约被钉住。
 *
 * 落点在 `packages/builder/test/`：本包同时依赖 `@ubean/scan` 与 `@ubean/vue`，
 * 且已有 `production-build.test.ts` 用 `scanProject` 的现成先例。
 */
import { mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';
import { afterEach, describe, expect, it } from 'vitest';
import { scanProject } from '@ubean/scan';
import { generateRouteFiles } from '@ubean/vue/generator';
import { join } from 'pathe';
import { generateOpenApiTypes } from '../src/codegen/index';

const REPO_ROOT = fileURLToPath(new URL('../../..', import.meta.url));
const FILE_MODE_EXAMPLE = join(REPO_ROOT, 'examples/routing-file-mode');
const GENERATED_DIR = join(FILE_MODE_EXAMPLE, 'src/router/_generated');
const BUNDLE_BASELINE = join(REPO_ROOT, 'examples/ubean-test/benchmarks/bundle-baseline.json');

let tmpDir: string | undefined;

afterEach(() => {
  if (tmpDir) rmSync(tmpDir, { recursive: true, force: true });
  tmpDir = undefined;
});

describe('TS-20 · 入库生成物可复现性守卫', () => {
  it('file-mode 示例的 routes.ts / imports.ts 可被重新生成且逐字节一致', async () => {
    const scan = await scanProject({ cwd: FILE_MODE_EXAMPLE, srcDir: 'src' });
    expect(scan.pages.map(p => p.name).sort()).toEqual(['About', 'Index', 'UsersId']);
    expect(scan.layouts.map(l => l.name)).toEqual(['default']);

    tmpDir = mkdtempSync(join(tmpdir(), 'ubean-artifact-regen-'));
    const result = await generateRouteFiles(scan, {
      cwd: FILE_MODE_EXAMPLE,
      // 必须是绝对路径：`generateRouteFiles` 不像 `scanPages` 那样把相对 srcDir 解析成绝对，
      // 传 `'src'` 会让 `relativePosix` 与绝对 `fullPath` 全不匹配，产出 `@/../Users/...` 的泄漏路径。
      srcDir: join(FILE_MODE_EXAMPLE, 'src'),
      outDir: tmpDir
    });

    for (const name of ['routes.ts', 'imports.ts'] as const) {
      const committed = readFileSync(join(GENERATED_DIR, name), 'utf8');
      const regenerated = readFileSync(join(tmpDir, name), 'utf8');
      expect(
        regenerated,
        `${name} 与入库版本不一致：生成器改了却没重新生成，或入库文件被手工编辑过。\n` +
          `重新生成请运行：pnpm --filter routing-file-mode build（或 dev 启动一次）`
      ).toBe(committed);
    }

    // 守卫的「有效性」自证：生成物不是空壳（空路由表也会「一致」，那样守卫毫无意义）
    expect(result.routeCount).toBe(3);
    expect(result.layoutCount).toBe(1);
  });
});

describe('TS-20 · typed-router.d.ts 契约', () => {
  it('产出三个模块增强块，且每个页面都有类型化的 RouteRecordInfo', async () => {
    const scan = await scanProject({ cwd: FILE_MODE_EXAMPLE, srcDir: 'src' });
    tmpDir = mkdtempSync(join(tmpdir(), 'ubean-artifact-dts-'));

    await generateRouteFiles(scan, {
      cwd: FILE_MODE_EXAMPLE,
      srcDir: join(FILE_MODE_EXAMPLE, 'src'),
      outDir: tmpDir
    });

    const dts = readFileSync(join(tmpDir, 'typed-router.d.ts'), 'utf8');

    // 三个模块增强块 —— 这是 vue-router 类型推断与 `@ubean/scan` 类型契约的接入点。
    // 注意：不断言头部注释，因为 typed-router 有**两个**写入器（generator 的
    // `@generated by @ubean/vue/generator` 与 `generateTypedRouter` 的
    // `// Generated by @ubean/vue — do not edit.`），头不是稳定契约，模块块才是。
    expect(dts).toContain(`declare module '@ubean/scan' {`);
    expect(dts).toContain(`declare module 'vue-router/auto-routes' {`);
    expect(dts).toContain(`declare module 'vue-router' {`);
    expect(dts).toContain('export interface RouteNamedMap {');
    expect(dts).toContain('RouteNamedMap: import(');

    // 形状契约：每个页面一条类型化条目（含动态参数的 ParamValue 收窄）
    expect(dts).toContain(`"About": RouteRecordInfo<"About", "/about", Record<never, never>, Record<never, never>>`);
    expect(dts).toContain(`"Index": RouteRecordInfo<"Index", "/", Record<never, never>, Record<never, never>>`);
    expect(dts).toContain(`"UsersId": RouteRecordInfo<"UsersId", "/users/:id", {`);
    expect(dts).toContain('id: ParamValue<true>');
    expect(dts).toContain('id: ParamValue<false>');

    // 路径映射与布局键（typed client / `useLocalePath` 侧消费）
    expect(dts).toContain('export type RouteLayoutKey = "default";');
    expect(dts).toContain('export type RouteKey = keyof RoutePathMap;');
    expect(dts).toMatch(/"UsersId": "\/users\/:id";/);
  });
});

describe('TS-20 · openapi.d.ts 契约', () => {
  it('头部标记 + 五个顶层 export + 路径键形态', async () => {
    tmpDir = mkdtempSync(join(tmpdir(), 'ubean-artifact-openapi-'));

    const filePath = await generateOpenApiTypes(
      {
        openapi: '3.1.0',
        info: { title: 'contract probe', version: '1.0.0' },
        paths: {
          '/api/hello': { get: { responses: { 200: { description: 'ok' } } } },
          '/api/users/{id}': { post: { responses: { 200: { description: 'ok' } } } }
        }
      },
      { outDir: tmpDir }
    );

    expect(filePath).toBe(join(tmpDir, 'openapi.d.ts'));
    const dts = readFileSync(filePath, 'utf8');

    // 头部三行是「这个文件是产物，不要手改」的唯一机器可读标记
    expect(
      dts.startsWith('// Auto-generated by ubean - do not edit manually\n/* eslint-disable */\n/* @ts-nocheck */\n')
    ).toBe(true);

    // 五个顶层 export —— typed client 的挂载点
    expect(dts).toContain('export interface paths {');
    expect(dts).toContain('export type webhooks = Record<string, never>;');
    expect(dts).toContain('export interface components {');
    expect(dts).toContain('export type $defs = Record<string, never>;');
    expect(dts).toContain('export type operations = Record<string, never>;');

    // 路径键形态：4 空格缩进 + 双引号（`openapi-typescript` 的稳定输出方言）
    const keys = [...dts.matchAll(/^ {4}"(\/[^"]*)": \{$/gm)].map(m => m[1]);
    expect(keys).toEqual(['/api/hello', '/api/users/{id}']);

    // 空 paths 时形态不同（`export type paths = Record<string, never>;`）——
    // 钉住这个分叉，免得写入器升级后静默换形态
    const emptyDir = mkdtempSync(join(tmpdir(), 'ubean-artifact-openapi-empty-'));
    try {
      const emptyPath = await generateOpenApiTypes(
        { openapi: '3.1.0', info: { title: 'empty', version: '1.0.0' }, paths: {} },
        { outDir: emptyDir }
      );
      const emptyDts = readFileSync(emptyPath, 'utf8');
      expect(emptyDts).toContain('export type paths = Record<string, never>;');
      expect(emptyDts).not.toContain('export interface paths {');
      expect(emptyDts).toContain('export type webhooks = Record<string, never>;');
    } finally {
      rmSync(emptyDir, { recursive: true, force: true });
    }
  });
});

describe('TS-20 · bundle-baseline.json 契约', () => {
  it('键与形状稳定，且总量字段与 entries 自洽', () => {
    const baseline = JSON.parse(readFileSync(BUNDLE_BASELINE, 'utf8')) as {
      generatedAt: string;
      outDir: string;
      entries: Array<{ file: string; bytes: number; gzip: number; brotli?: number; isEntry?: boolean }>;
      totalBytes: number;
      totalGzip: number;
      totalBrotli: number;
      entryGzip: number;
    };

    // 形状：`analyze-lib` 的 `BundleBaseline` 是 `compareBundleBaseline` 的输入契约
    expect(typeof baseline.generatedAt).toBe('string');
    expect(Number.isNaN(Date.parse(baseline.generatedAt))).toBe(false);
    expect(baseline.outDir).toBe('dist/public');
    expect(Array.isArray(baseline.entries)).toBe(true);
    expect(baseline.entries.length).toBeGreaterThan(0);

    for (const entry of baseline.entries) {
      expect(typeof entry.file).toBe('string');
      expect(entry.bytes).toBeGreaterThan(0);
      expect(entry.gzip).toBeGreaterThan(0);
      // 压缩率只对「够大」的 chunk 有意义：gzip 有 ~18B 头 + 8B 尾的开销，
      // 小文件（实测 `_plugin-vue_export-helper` 84B → 99B）压完反而更大。
      if (entry.bytes > 1024) expect(entry.gzip).toBeLessThan(entry.bytes);
    }

    // 自洽：总量字段必须等于 entries 的聚合，否则相对门禁与绝对上限都在比错的数
    const sum = (pick: (e: (typeof baseline.entries)[number]) => number): number =>
      baseline.entries.reduce((total, entry) => total + pick(entry), 0);
    expect(baseline.totalGzip).toBe(sum(e => e.gzip));
    expect(baseline.totalBytes).toBe(sum(e => e.bytes));
    expect(baseline.entryGzip).toBe(sum(e => (e.isEntry ? e.gzip : 0)));
    expect(baseline.totalBrotli).toBe(sum(e => e.brotli ?? 0));

    // 必须恰好有一条 entry chunk —— `--max-entry-kb` 断言的就是它
    expect(baseline.entries.filter(e => e.isEntry)).toHaveLength(1);

    // 刻意**不**与磁盘上的 `dist/` 比对：`dist` 是提交过的陈旧产物，
    // 拿它当基线等于测上一个版本（TS-33 记录过同一坑）。
  });
});
