import { defineVirtualModule } from '../build/virtual/registry';
import type { ScannedPageRoute, ScannedLayout, ScannedAppEntry } from '../routing/types';

export function createVuePagesVirtualModule(pages: ScannedPageRoute[], layouts: ScannedLayout[]) {
  return defineVirtualModule('#ubean-pages', () => {
    const pageEntries: string[] = [];
    for (const p of pages) {
      pageEntries.push(
        `  ${JSON.stringify(p.name)}: () => import(${JSON.stringify(`/src/pages/${p.relativePath}`)}).then(m => m.default || m)`
      );
    }

    const layoutEntries: string[] = [];
    for (const l of layouts) {
      layoutEntries.push(
        `  ${JSON.stringify(l.name)}: () => import(${JSON.stringify(`/src/layouts/${l.relativePath}`)}).then(m => m.default || m)`
      );
    }

    const defaultLayout = layouts.find(l => l.isDefault);

    const pageNames = pages.map(p => JSON.stringify(p.name)).join(' | ') || 'string';
    const layoutNames = layouts.map(l => JSON.stringify(l.name)).join(' | ') || 'string';

    return `${`
// Auto-generated by ubean - do not edit
/* eslint-disable */

const _pageLoaders = {
${pageEntries.join(',\n')}
};

const _layoutLoaders = {
${layoutEntries.join(',\n')}
};

export const pageNames = [${pages.map(p => JSON.stringify(p.name)).join(', ')}] as const;
export const layoutNames = [${layouts.map(l => JSON.stringify(l.name)).join(', ')}] as const;
export const defaultLayout = ${defaultLayout ? JSON.stringify(defaultLayout.name) : 'null'} as const;

export type RouteName = ${pageNames};
export type LayoutName = ${layoutNames};

export function resolvePageComponent(name: string): Promise<any> {
  const loader = _pageLoaders[name];
  if (!loader) {
    return Promise.reject(new Error('[ubean] Page component not found: ' + name));
  }
  return loader();
}

export function resolveLayoutComponent(name: string | false | null | undefined): Promise<any> {
  if (!name || name === false) return Promise.resolve(null);
  const loader = _layoutLoaders[name];
  if (!loader) {
    return Promise.reject(new Error('[ubean] Layout component not found: ' + name));
  }
  return loader();
}

export const pages = {
${pages.map(p => `  ${JSON.stringify(p.name)}: { name: ${JSON.stringify(p.name)}, route: ${JSON.stringify(p.route)}, path: ${JSON.stringify(p.path)}, layout: ${JSON.stringify(p.layout)} }`).join(',\n')}
};

export const layouts = {
${layouts.map(l => `  ${JSON.stringify(l.name)}: { name: ${JSON.stringify(l.name)}, isDefault: ${l.isDefault} }`).join(',\n')}
};

export default {
  pageNames,
  layoutNames,
  defaultLayout,
  resolvePageComponent,
  resolveLayoutComponent,
  pages,
  layouts
};
`.trim()}\n`;
  });
}

const EMPTY_APP_ENTRY: ScannedAppEntry = {
  shared: { exists: false },
  server: { exists: false },
  client: { exists: false }
};

export function createVueAppEntryVirtualModule(appEntry: ScannedAppEntry = EMPTY_APP_ENTRY, srcDir: string = 'src') {
  return defineVirtualModule('#ubean-app', () => {
    const hasSharedApp = appEntry.shared.exists;
    const hasServerApp = appEntry.server.exists;
    const hasClientApp = appEntry.client.exists;

    const srcPrefix = srcDir.startsWith('/') ? srcDir : `/${srcDir}`;
    const sharedImport = hasSharedApp
      ? `import _sharedApp from ${JSON.stringify(`${srcPrefix}/${appEntry.shared.relativePath}`)};`
      : 'const _sharedApp = null;';
    const serverImport = hasServerApp
      ? `import _serverApp from ${JSON.stringify(`${srcPrefix}/${appEntry.server.relativePath}`)};`
      : 'const _serverApp = null;';
    const clientImport = hasClientApp
      ? `import _clientApp from ${JSON.stringify(`${srcPrefix}/${appEntry.client.relativePath}`)};`
      : 'const _clientApp = null;';

    return `${`
// Auto-generated by ubean - do not edit
/* eslint-disable */
import { createApp as _createVueApp } from 'vue';
${sharedImport}
${serverImport}
${clientImport}

export {
  createUbeanApp,
  createUbeanSSRApp,
  usePage,
  useRouter,
  useHead,
  Link,
  Head
} from 'ubean/vue-runtime/app';

export {
  createUbeanClient,
  getInitialPageData
} from 'ubean/vue-runtime';

export { createHeadManager } from 'ubean/vue-runtime';
export { defineApp, applyAppConfig, createDefaultAppConfig } from 'ubean/vue-runtime/define-app';

export {
  resolvePageComponent,
  resolveLayoutComponent,
  defaultLayout,
  pageNames,
  layoutNames
} from '#ubean-pages';

export type { RouteName, LayoutName } from '#ubean-pages';

function _mergeAppConfig(base, ...configs) {
  const result = { ...base };
  for (const cfg of configs) {
    if (!cfg) continue;
    if (cfg.plugins) result.plugins = [...(result.plugins || []), ...cfg.plugins];
    if (cfg.globalComponents) result.globalComponents = { ...(result.globalComponents || {}), ...cfg.globalComponents };
    if (cfg.provides) result.provides = { ...(result.provides || {}), ...cfg.provides };
    if (cfg.head) result.head = { ...(result.head || {}), ...cfg.head };
    if (cfg.rootId) result.rootId = cfg.rootId;
    if (cfg.rootAttrs) result.rootAttrs = { ...(result.rootAttrs || {}), ...cfg.rootAttrs };
    if (cfg.onAppCreated) result._onAppCreated = cfg.onAppCreated;
    if (cfg.onClientReady) result._onClientReady = cfg.onClientReady;
    if (cfg.errorComponent) result.errorComponent = cfg.errorComponent;
    if (cfg.loadingComponent) result.loadingComponent = cfg.loadingComponent;
  }
  return result;
}

export function resolveAppConfig(mode) {
  const base = createDefaultAppConfig();
  if (!_sharedApp && !_serverApp && !_clientApp) return base;

  const sharedCfg = typeof _sharedApp === 'function' ? _sharedApp() : _sharedApp;
  const serverCfg = mode === 'server' && _serverApp ? (typeof _serverApp === 'function' ? _serverApp() : _serverApp) : null;
  const clientCfg = mode === 'client' && _clientApp ? (typeof _clientApp === 'function' ? _clientApp() : _clientApp) : null;

  const merged = _mergeAppConfig(base, sharedCfg, mode === 'server' ? serverCfg : clientCfg);

  if (sharedCfg?.onAppCreated) merged._onAppCreated = sharedCfg.onAppCreated;
  if (mode === 'client' && clientCfg?.onClientReady) merged._onClientReady = clientCfg.onClientReady;
  else if (mode === 'server' && serverCfg?.onAppCreated) merged._onAppCreated = serverCfg.onAppCreated;

  return merged;
}

export function createApp() {
  const config = resolveAppConfig('client');

  const instance = createUbeanApp({
    resolvePageComponent,
    resolveLayoutComponent,
    defaultLayout
  });

  applyAppConfig(instance.app, config, 'client');

  if (config._onAppCreated) config._onAppCreated(instance.app);

  instance.app.mount('#' + (config.rootId || 'app'));

  if (config._onClientReady) config._onClientReady(instance.app);

  return instance;
}

export function createSSRApp(initialPage) {
  const config = resolveAppConfig('server');

  const app = createUbeanSSRApp(initialPage, {
    resolvePageComponent,
    resolveLayoutComponent,
    defaultLayout
  });

  applyAppConfig(app, config, 'server');

  if (config._onAppCreated) config._onAppCreated(app);

  return { app, config };
}

export const rootId = 'app';
`.trim()}\n`;
  });
}

export function createClientEntryVirtualModule() {
  return defineVirtualModule('#ubean-client-entry', () => {
    return `${`
// Auto-generated by ubean client entry - do not edit
/* eslint-disable */
import { createApp } from '#ubean-app';
createApp();
`.trim()}\n`;
  });
}
