import { defineVirtualModule } from '../build/virtual/registry';
import type { ScannedPageRoute, ScannedLayout, ScannedAppEntry, ScannedServerEntry } from '../routing/types';

/**
 * Convert ubean route path to vue-router compatible path.
 * - `**:param` (catch-all) → `:param(.*)*`
 * - `:param?` (optional) → `:param?` (already compatible)
 * - `:param` (dynamic) → `:param` (already compatible)
 */
function toVueRouterPath(route: string): string {
  return route.replace(/\*\*:(\w[\w-]*)/g, ':$1(.*)*');
}

export function createVuePagesVirtualModule(pages: ScannedPageRoute[], layouts: ScannedLayout[]) {
  return defineVirtualModule('virtual:ubean-pages', () => {
    const pageLoaders: string[] = [];
    const layoutLoaders: string[] = [];
    const routeEntries: string[] = [];

    for (const p of pages) {
      const varName = `Page_${p.name.replace(/[^a-zA-Z0-9]/g, '_')}`;
      const routerPath = toVueRouterPath(p.route);
      const layoutValue = p.layout === false ? 'false' : p.layout ? JSON.stringify(p.layout) : 'undefined';
      const cacheValue = p.cache === true ? 'true' : 'undefined';

      pageLoaders.push(`const ${varName} = () => import(${JSON.stringify(p.fullPath)}).then(m => m.default || m);`);
      routeEntries.push(
        `  { path: ${JSON.stringify(routerPath)}, name: ${JSON.stringify(p.name)}, component: ${varName}, meta: { layout: ${layoutValue}, pageName: ${JSON.stringify(p.name)}, cache: ${cacheValue} } }`
      );
    }

    for (const l of layouts) {
      const varName = `Layout_${l.name.replace(/[^a-zA-Z0-9]/g, '_')}`;
      layoutLoaders.push(`const ${varName} = () => import(${JSON.stringify(l.fullPath)}).then(m => m.default || m);`);
    }

    const defaultLayout = layouts.find(l => l.isDefault);
    const defaultLayoutName = defaultLayout ? defaultLayout.name : 'null';

    // Build layout loader map
    const layoutLoaderMap = layouts
      .map(l => {
        const varName = `Layout_${l.name.replace(/[^a-zA-Z0-9]/g, '_')}`;
        return `  ${JSON.stringify(l.name)}: ${varName}`;
      })
      .join(',\n');

    return `${`
// Auto-generated by ubean - do not edit
/* eslint-disable */

${pageLoaders.join('\n')}
${layoutLoaders.join('\n')}

export const routes = [
${routeEntries.join(',\n')}
];

const _layoutLoaders = {
${layoutLoaderMap}
};

const _pageLoaders = {
${pages.map(p => `  ${JSON.stringify(p.name)}: ${`Page_${p.name.replace(/[^a-zA-Z0-9]/g, '_')}`}`).join(',\n')}
};

export const pageNames = [${pages.map(p => JSON.stringify(p.name)).join(', ')}] as const;
export const layoutNames = [${layouts.map(l => JSON.stringify(l.name)).join(', ')}] as const;
export const defaultLayout = ${defaultLayoutName === 'null' ? 'null' : JSON.stringify(defaultLayoutName)} as const;

export type RouteName = (typeof pageNames)[number];
export type LayoutName = (typeof layoutNames)[number];

export function resolvePageComponent(name) {
  const loader = _pageLoaders[name];
  if (!loader) {
    return Promise.reject(new Error('[ubean] Page component not found: ' + name));
  }
  return loader();
}

export function resolveLayoutComponent(name) {
  if (!name) return Promise.resolve(null);
  const loader = _layoutLoaders[name];
  if (!loader) {
    return Promise.resolve(null);
  }
  return loader();
}

export const pages = {
${pages.map(p => `  ${JSON.stringify(p.name)}: { name: ${JSON.stringify(p.name)}, route: ${JSON.stringify(p.route)}, path: ${JSON.stringify(p.path)}, layout: ${JSON.stringify(p.layout)} }`).join(',\n')}
};

export const layouts = {
${layouts.map(l => `  ${JSON.stringify(l.name)}: { name: ${JSON.stringify(l.name)}, isDefault: ${l.isDefault} }`).join(',\n')}
};

export default {
  routes,
  pageNames,
  layoutNames,
  defaultLayout,
  resolvePageComponent,
  resolveLayoutComponent,
  pages,
  layouts
};
`.trim()}\n`;
  });
}

const EMPTY_APP_ENTRY: ScannedAppEntry = {
  shared: { exists: false },
  server: { exists: false },
  client: { exists: false }
};

export function createVueAppEntryVirtualModule(appEntry: ScannedAppEntry = EMPTY_APP_ENTRY) {
  return defineVirtualModule('virtual:ubean-app', () => {
    const hasSharedApp = appEntry.shared.exists;
    const hasServerApp = appEntry.server.exists;
    const hasClientApp = appEntry.client.exists;

    const sharedImport = hasSharedApp
      ? `import _sharedApp from ${JSON.stringify(appEntry.shared.fullPath)};`
      : 'const _sharedApp = null;';
    const serverImport = hasServerApp
      ? `import _serverApp from ${JSON.stringify(appEntry.server.fullPath)};`
      : 'const _serverApp = null;';
    const clientImport = hasClientApp
      ? `import _clientApp from ${JSON.stringify(appEntry.client.fullPath)};`
      : 'const _clientApp = null;';

    return `${`
// Auto-generated by ubean - do not edit
/* eslint-disable */
${sharedImport}
${serverImport}
${clientImport}

import {
  createUbeanApp,
  createUbeanSSRApp,
  usePage,
  useRouter,
  useHead,
  useSeoMeta,
  Link,
  Head,
  getInitialPageData,
  defineApp,
  applyAppConfig,
  createDefaultAppConfig
} from 'ubean/runtime/vue';
import { createHead as createClientHead } from '@unhead/vue/client';
import { createHead as createServerHead } from '@unhead/vue/server';

export {
  createUbeanApp,
  createUbeanSSRApp,
  usePage,
  useRouter,
  useHead,
  useSeoMeta,
  Link,
  Head,
  getInitialPageData,
  defineApp,
  applyAppConfig,
  createDefaultAppConfig
};

import {
  routes,
  resolvePageComponent,
  resolveLayoutComponent,
  defaultLayout,
  pageNames,
  layoutNames
} from 'virtual:ubean-pages';

export {
  routes,
  resolvePageComponent,
  resolveLayoutComponent,
  defaultLayout,
  pageNames,
  layoutNames
};

function _mergeAppConfig(base, ...configs) {
  const result = { ...base };
  for (const cfg of configs) {
    if (!cfg) continue;
    if (cfg.plugins) result.plugins = [...(result.plugins || []), ...cfg.plugins];
    if (cfg.globalComponents) result.globalComponents = { ...(result.globalComponents || {}), ...cfg.globalComponents };
    if (cfg.provides) result.provides = { ...(result.provides || {}), ...cfg.provides };
    if (cfg.head) result.head = { ...(result.head || {}), ...cfg.head };
    if (cfg.rootId) result.rootId = cfg.rootId;
    if (cfg.rootAttrs) result.rootAttrs = { ...(result.rootAttrs || {}), ...cfg.rootAttrs };
    if (cfg.onAppCreated) result.onAppCreated = cfg.onAppCreated;
    if (cfg.onClientReady) result.onClientReady = cfg.onClientReady;
    if (cfg.errorComponent) result.errorComponent = cfg.errorComponent;
    if (cfg.loadingComponent) result.loadingComponent = cfg.loadingComponent;
    if (cfg.viewTransitions !== undefined) result.viewTransitions = cfg.viewTransitions;
  }
  return result;
}

export function resolveAppConfig(mode) {
  const base = createDefaultAppConfig();
  if (!_sharedApp && !_serverApp && !_clientApp) return base;

  const sharedCfg = typeof _sharedApp === 'function' ? _sharedApp() : _sharedApp;
  const serverCfg = mode === 'server' && _serverApp ? (typeof _serverApp === 'function' ? _serverApp() : _serverApp) : null;
  const clientCfg = mode === 'client' && _clientApp ? (typeof _clientApp === 'function' ? _clientApp() : _clientApp) : null;

  const merged = _mergeAppConfig(base, sharedCfg, mode === 'server' ? serverCfg : clientCfg);

  // onAppCreated: shared config is the default; server/client-specific overrides it if present.
  if (sharedCfg?.onAppCreated) merged.onAppCreated = sharedCfg.onAppCreated;
  if (mode === 'client' && clientCfg?.onClientReady) merged.onClientReady = clientCfg.onClientReady;
  else if (mode === 'server' && serverCfg?.onAppCreated) merged.onAppCreated = serverCfg.onAppCreated;

  return merged;
}

export function createApp() {
  const config = resolveAppConfig('client');
  const head = createClientHead();

  // Push global app head (from defineApp) as defaults before any page-level head.
  if (config.head) {
    const headInput = {};
    if (config.head.title) headInput.title = config.head.title;
    if (config.head.htmlAttrs) headInput.htmlAttrs = config.head.htmlAttrs;
    if (config.head.bodyAttrs) headInput.bodyAttrs = config.head.bodyAttrs;
    if (config.head.meta) headInput.meta = config.head.meta;
    if (config.head.link) headInput.link = config.head.link;
    if (config.head.script) headInput.script = config.head.script;
    head.push(headInput);
  }

  const initialPage = getInitialPageData();
  const instance = createUbeanApp({
    routes,
    resolveLayoutComponent,
    defaultLayout,
    head,
    viewTransitions: config.viewTransitions,
    initialPage: initialPage || undefined,
    hydrate: !!initialPage
  });

  applyAppConfig(instance.app, config, 'client');

  if (config.onAppCreated) config.onAppCreated(instance.app);

  const mountApp = () => {
    instance.app.mount('#' + (config.rootId || 'app'));
    if (config.onClientReady) {
      config.onClientReady(instance.app);
    }
  };

  // When hydrating SSR content, must wait for router to be ready before mounting,
  // otherwise RouterView has no matched route and causes hydration mismatch.
  if (initialPage) {
    instance.router.isReady().then(mountApp);
  } else {
    mountApp();
  }

  return instance;
}

export function createSSRApp(initialPage) {
  const config = resolveAppConfig('server');
  const head = createServerHead();

  const { app, router } = createUbeanSSRApp(initialPage, {
    routes,
    resolveLayoutComponent,
    defaultLayout,
    head
  });

  applyAppConfig(app, config, 'server');

  if (config.onAppCreated) config.onAppCreated(app);

  return { app, router, head, config };
}

export const rootId = 'app';
`.trim()}\n`;
  });
}

export function createClientEntryVirtualModule() {
  return defineVirtualModule('virtual:ubean-client-entry', () => {
    return `${`
// Auto-generated by ubean client entry - do not edit
/* eslint-disable */
import { createApp } from 'virtual:ubean-app';

createApp();
`.trim()}\n`;
  });
}

const EMPTY_SERVER_ENTRY: ScannedServerEntry = {
  shared: { exists: false },
  dev: { exists: false },
  prod: { exists: false }
};

export function createServerEntryVirtualModule(serverEntry: ScannedServerEntry = EMPTY_SERVER_ENTRY) {
  return defineVirtualModule('virtual:ubean-server', () => {
    const hasShared = serverEntry.shared.exists;
    const hasDev = serverEntry.dev.exists;
    const hasProd = serverEntry.prod.exists;

    const sharedImport = hasShared
      ? `import _sharedServer from ${JSON.stringify(serverEntry.shared.fullPath)};`
      : 'const _sharedServer = null;';
    const devImport = hasDev
      ? `import _devServer from ${JSON.stringify(serverEntry.dev.fullPath)};`
      : 'const _devServer = null;';
    const prodImport = hasProd
      ? `import _prodServer from ${JSON.stringify(serverEntry.prod.fullPath)};`
      : 'const _prodServer = null;';

    return `${`
// Auto-generated by ubean server entry - do not edit
/* eslint-disable */
${sharedImport}
${devImport}
${prodImport}

import {
  defineServer,
  createDefaultServerConfig,
  mergeServerConfigs
} from 'ubean/runtime/app';

export {
  defineServer,
  createDefaultServerConfig,
  mergeServerConfigs
};

/**
 * Resolve the user's server config for the given mode ('dev' | 'prod').
 * Merges shared config with mode-specific config. Returns an empty
 * config when no server entry file exists.
 */
export function resolveServerConfig(mode) {
  const base = createDefaultServerConfig();

  if (!_sharedServer && !_devServer && !_prodServer) return base;

  const sharedCfg = typeof _sharedServer === 'function' ? _sharedServer() : _sharedServer;
  const modeCfg = mode === 'dev'
    ? (typeof _devServer === 'function' ? _devServer() : _devServer)
    : (typeof _prodServer === 'function' ? _prodServer() : _prodServer);

  return mergeServerConfigs(base, sharedCfg, modeCfg);
}
`.trim()}\n`;
  });
}
