/**
 * P9-20: MDX real compilation.
 *
 * Compiles MDX (Markdown + JSX) files to Vue components using `@mdx-js/mdx`
 * as an optional peer dependency. The compiled output uses ubean's Vue JSX
 * runtime (`@ubean/markdown/jsx-runtime`) which maps JSX calls to Vue's `h()`.
 *
 * Features:
 * - Frontmatter extraction (YAML)
 * - JSX component support in Markdown
 * - Vue component imports
 * - Code highlighting via remark/rehype plugins
 * - Graceful fallback to plain Markdown when `@mdx-js/mdx` is not installed
 *
 * Usage:
 * ```typescript
 * import { compileMdx } from '@ubean/markdown/mdx';
 *
 * const result = await compileMdx(mdxSource, {
 *   filePath: 'post.mdx',
 *   remarkPlugins: [remarkGfm],
 * });
 * // result.code → JavaScript module string (Vue component)
 * // result.frontmatter → parsed frontmatter
 * ```
 */
import { markdownToHtml, parseFrontmatter } from './index';
import type { MarkdownFrontmatter } from './index';

export interface MdxOptions {
  /** File path (for error reporting and relative imports). */
  filePath?: string;
  /** Additional remark plugins. */
  remarkPlugins?: any[];
  /** Additional rehype plugins. */
  rehypePlugins?: any[];
  /** Whether to output development or production code. */
  development?: boolean;
}

export interface MdxCompileResult {
  /** Compiled JavaScript module string. */
  code: string;
  /** Parsed frontmatter. */
  frontmatter: MarkdownFrontmatter;
  /** Whether MDX compiler was available (true) or fell back to plain markdown. */
  compiled: boolean;
}

let _mdxCompiler: any | null | undefined;

/**
 * Dynamically load `@mdx-js/mdx` (optional peer dependency).
 * Returns null if not installed.
 */
async function getMdxCompiler(): Promise<any | null> {
  if (_mdxCompiler !== undefined) return _mdxCompiler;
  try {
    const mod = await import('@mdx-js/mdx');
    _mdxCompiler = (mod as any).compile || (mod as any).default || null;
  } catch {
    _mdxCompiler = null;
  }
  return _mdxCompiler;
}

/**
 * Check if `@mdx-js/mdx` is available for real MDX compilation.
 */
export async function isMdxAvailable(): Promise<boolean> {
  const compiler = await getMdxCompiler();
  return compiler !== null;
}

/**
 * Compile MDX source to a Vue component JavaScript module.
 *
 * Uses `@mdx-js/mdx` to compile the MDX body to a JS module that imports
 * from `@ubean/markdown/jsx-runtime` (which maps to Vue's `h()` function).
 *
 * If `@mdx-js/mdx` is not installed, falls back to plain markdown rendering
 * using `markdown-exit`, wrapping the HTML output in a Vue component.
 *
 * @param source Raw MDX source string (with optional frontmatter)
 * @param options Compilation options
 * @returns Compilation result with code, frontmatter, and compiled flag
 */
export async function compileMdx(source: string, options: MdxOptions = {}): Promise<MdxCompileResult> {
  const { data: frontmatter, content } = parseFrontmatter(source);
  const compiler = await getMdxCompiler();

  if (compiler) {
    // Real MDX compilation using @mdx-js/mdx
    // Note: MDX v3 removed the `filepath` option; pass a VFile-like object
    // with `path` set so error messages include the file path.
    const input = options.filePath ? { path: options.filePath, value: content } : content;
    const compiled = await compiler(input, {
      format: 'mdx',
      // jsxImportSource tells MDX where to import jsx/jsxs/Fragment from.
      // MDX appends `/jsx-runtime` to this value, so pointing at
      // '@ubean/markdown' produces imports from '@ubean/markdown/jsx-runtime',
      // which matches the package's `./jsx-runtime` export.
      jsxImportSource: '@ubean/markdown',
      development: options.development ?? false,
      remarkPlugins: options.remarkPlugins || [],
      rehypePlugins: options.rehypePlugins || []
    });

    const code = String(compiled);
    return { code, frontmatter, compiled: true };
  }

  // Fallback: treat MDX as plain Markdown and wrap in a Vue component
  const html = markdownToHtml(content);
  const escapedHtml = JSON.stringify(html);
  const code = generateFallbackComponent(escapedHtml, frontmatter);
  return { code, frontmatter, compiled: false };
}

/**
 * Generate a fallback Vue component when `@mdx-js/mdx` is not available.
 * Renders the markdown HTML using `v-html`.
 */
function generateFallbackComponent(htmlJson: string, frontmatter: MarkdownFrontmatter): string {
  const frontmatterExport =
    Object.keys(frontmatter).length > 0
      ? `export const frontmatter = ${JSON.stringify(frontmatter)};`
      : 'export const frontmatter = {};';

  return `// Auto-generated by @ubean/markdown (fallback mode — @mdx-js/mdx not installed)
import { defineComponent, h } from 'vue';
${frontmatterExport}
export default defineComponent({
  name: 'MdxPage',
  setup() {
    return () => h('div', { class: 'ubean-mdx-content', innerHTML: ${htmlJson} });
  }
});
`;
}

/**
 * Synchronously check if MDX compilation is available (without dynamic import).
 * Uses the cached result from a previous `compileMdx()` or `isMdxAvailable()` call.
 */
export function isMdxAvailableSync(): boolean {
  return _mdxCompiler !== undefined && _mdxCompiler !== null;
}
