packages:
  - 'packages/*'
  - 'apps/*'
  - 'examples/*'
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.3.1
  vite-plus: 0.3.1
  typescript: npm:typescript-native-bridge@latest
  vue-i18n: 11.4.10
  '@intlify/core': 11.4.10
  '@intlify/unplugin-vue-i18n': 11.2.5
overrides:
  vite: 'catalog:'
  typescript: 'catalog:'
shamefullyHoist: true
ignoreWorkspaceRootCheck: true
allowBuilds:
  electron: false
  esbuild: false
minimumReleaseAge: 0
