import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { defineConfig } from 'ubean';
import { SHIKI_THEMES } from './src/shared/shiki-config';
import { collectPrerenderRoutes } from './build/docs-routes';
import { createMarkdownHighlight } from './build/highlight';

const rootDir = path.dirname(fileURLToPath(import.meta.url));

const highlightCode = await createMarkdownHighlight();

/**
 * Concrete prerender routes: static shell pages + default-locale content slugs
 * (+ zh-only pages) mapped through the shared route model in
 * `build/docs-routes.ts`. Dynamic param routes are not expanded by
 * `prerender.all`, so content must be listed explicitly; the `/zh` mirrors are
 * generated by the SSG renderer's `expandRoutes` (`prefix_except_default`)
 * instead of being listed.
 */
const prerenderRoutes = await collectPrerenderRoutes(rootDir);

export default defineConfig({
  mode: 'ssg',
  srcDir: 'src',

  favicon: 'https://r2.soybeanjs.tech/soybeanjs/logo-ubean.svg?v=202608211738',

  i18n: {
    defaultLocale: 'en',
    locales: [
      { code: 'en', language: 'en', name: 'English' },
      { code: 'zh', language: 'zh-CN', name: '中文', dir: 'ltr' }
    ],
    strategy: 'prefix_except_default',
    detectBrowserLanguage: false
  },

  markdown: {
    wrapperClass: 'markdown-wrapper',
    theme: {
      light: SHIKI_THEMES.light,
      dark: SHIKI_THEMES.dark
    },
    markdownExit: {
      highlight: highlightCode
    }
  },

  // @vean/ui in UnoCSS mode: styling comes from presetUi in uno.config.ts, and
  // `ui: true` registers `@vean/ui/resolver` for S* component auto-import.
  ui: { css: false },

  // Theme state is owned by @vean/theme (createThemeInitScript in app.ts);
  // disabling the built-in colorMode avoids a second, conflicting source.
  colorMode: false,

  // Full-text content search (@ubean/content). Each locale is its own collection
  // so the client can filter by the active language: `__search.json` becomes
  // `{ en: [...], zh: [...] }`. The zh source gets a `/zh` prefix so hit ids
  // already carry the `prefix_except_default` locale prefix.
  content: {
    sources: {
      en: { dir: 'src/content/en' },
      zh: { dir: 'src/content/zh', prefix: '/zh' }
    }
  },

  prerender: {
    include: prerenderRoutes,
    crawlLinks: true
  },

  autoImports: {
    // vue-router (`useRoute`/`useRouter`) and vue-i18n (`useI18n`) come from their
    // own packages — ubean does not re-export them, so the auto-import presets
    // point at the packages directly.
    vueRouter: true,
    vueI18n: true,
    dirs: ['src/composables']
  },
  components: {
    dirs: ['src/components']
  },

  dev: {
    host: '0.0.0.0'
  }
});
