// @generated by @ubean/routing/generator — do not edit manually.
// This file is regenerated on every dev start / build.

export type LayoutKey = 'default';
export type RouteKey = 'About' | 'Index' | 'UsersId';

export type Lazy<T> = () => Promise<T>;
export type RawRouteComponent = import('vue').Component | Lazy<import('vue').Component>;

export interface RouteRecord {
  name: RouteKey;
  path: string;
  component: string;
  layout?: LayoutKey | false;
  reuse?: boolean;
  meta?: Record<string, unknown>;
  cache?: boolean;
  requiresAuth?: boolean;
  middleware?: string | string[];
}

export const layouts: Record<LayoutKey, RawRouteComponent> = {
  default: () => import('@/src/layouts/default')
};

export const views: Record<RouteKey, RawRouteComponent> = {
  About: () => import('@/src/pages/about'),
  Index: () => import('@/src/pages/index'),
  UsersId: () => import('@/src/pages/users/[id]')
};
