// @generated by @ubean/routing/generator — do not edit manually.
// This file is regenerated on every dev start / build.

import type { RouteRecord } from './imports';

export const routes: RouteRecord[] = [
  {
    name: 'About',
    path: '/about',
    component: '@/src/pages/about'
  },
  {
    name: 'Index',
    path: '/',
    component: '@/src/pages/index'
  },
  {
    name: 'UsersId',
    path: '/users/:id',
    component: '@/src/pages/users/[id]'
  }
];
