// @generated by @ubean/routing/generator — do not edit manually.
// This file is regenerated on every dev start / build.

import type { RouteRecord } from './imports';

export const routes: RouteRecord[] = [
  {
    name: "About",
    path: "/about",
    component: "About"
  },
  {
    name: "Index",
    path: "/",
    component: "Index"
  },
  {
    name: "UsersId",
    path: "/users/:id",
    component: "UsersId"
  }
];
