import { writeFile, mkdir } from 'node:fs/promises';
import { join } from 'pathe';
import { generateAutoImports } from '../auto-imports';
import type { AutoImportOptions } from '../auto-imports';
import type { ScanResult } from '../routing/types';

export interface CodegenOptions extends Omit<AutoImportOptions, 'cwd' | 'srcDir' | 'buildDir'> {
  cwd: string;
  srcDir: string;
  buildDir: string;
}

export interface CodegenResult {
  routeTypesPath: string;
  pageTypesPath: string;
  autoImportsDtsPath?: string;
  componentsDtsPath?: string;
  generated: string[];
}

export async function generateTypes(result: ScanResult, options: CodegenOptions): Promise<CodegenResult> {
  const { cwd, srcDir, buildDir, ...autoImportOptions } = options;
  const outDir = join(cwd, buildDir);
  await mkdir(outDir, { recursive: true });

  const generated: string[] = [];

  const routeTypes = generateRouteTypes(result);
  const routeTypesPath = join(outDir, 'routes.d.ts');
  await writeFile(routeTypesPath, routeTypes, 'utf-8');
  generated.push(routeTypesPath);

  const pageTypes = generatePageTypes(result);
  const pageTypesPath = join(outDir, 'pages.d.ts');
  await writeFile(pageTypesPath, pageTypes, 'utf-8');
  generated.push(pageTypesPath);

  let autoImportsDtsPath: string | undefined;
  let componentsDtsPath: string | undefined;

  const autoImportsResult = await generateAutoImports(result, {
    cwd,
    srcDir,
    buildDir,
    ...autoImportOptions
  });

  autoImportsDtsPath = autoImportsResult.autoImportsDtsPath;
  componentsDtsPath = autoImportsResult.componentsDtsPath;
  generated.push(autoImportsDtsPath, componentsDtsPath);

  return { routeTypesPath, pageTypesPath, autoImportsDtsPath, componentsDtsPath, generated };
}

function generateRouteTypes(result: ScanResult): string {
  const apiRoutes = result.apiRoutes;

  const lines: string[] = [
    '// Auto-generated by ubean - do not edit manually',
    '/* eslint-disable */',
    '// @ts-nocheck',
    '',
    'declare module "ubean:routes" {',
    '  export interface ApiRoute {',
    '    method: string;',
    '    path: string;',
    '    filePath: string;',
    '    meta?: Record<string, unknown>;',
    '  }',
    ''
  ];

  const routeEntries = apiRoutes.map(
    r => `    "${r.method?.toUpperCase() || 'ALL'} ${r.route}": { filePath: ${JSON.stringify(r.fullPath)} }`
  );

  if (routeEntries.length > 0) {
    lines.push('  export type ApiRouteMap = {');
    lines.push(routeEntries.join(';\n'));
    lines.push('  };');
  } else {
    lines.push('  export type ApiRouteMap = {};');
  }

  lines.push('');

  const routePaths = [...new Set(apiRoutes.map(r => r.route))].sort();
  if (routePaths.length > 0) {
    lines.push('  export type ApiRoutePath =');
    lines.push(routePaths.map(p => `    | ${JSON.stringify(p)}`).join('\n'));
    lines.push('  ;');
  } else {
    lines.push('  export type ApiRoutePath = string;');
  }

  lines.push('');

  const routeMethods = [...new Set(apiRoutes.map(r => r.method?.toUpperCase()).filter(Boolean))].sort();
  if (routeMethods.length > 0) {
    lines.push('  export type ApiMethod =');
    lines.push(routeMethods.map(m => `    | ${JSON.stringify(m)}`).join('\n'));
    lines.push('  ;');
  } else {
    lines.push('  export type ApiMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE" | "OPTIONS" | "HEAD";');
  }

  lines.push('');
  lines.push('  export const routes: ApiRoute[];');
  lines.push('  export const middlewares: { filePath: string; order: number; global: boolean }[];');
  lines.push('}');

  return `${lines.join('\n')}\n`;
}

function generatePageTypes(result: ScanResult): string {
  const pages = result.pages;
  const layouts = result.layouts;

  const lines: string[] = [
    '// Auto-generated by ubean - do not edit manually',
    '/* eslint-disable */',
    '// @ts-nocheck',
    '',
    'declare module "ubean:pages" {',
    '  export interface PageInfo {',
    '    name: string;',
    '    path: string;',
    '    filePath: string;',
    '    layout?: string;',
    '    reuseTarget?: string;',
    '  }',
    '',
    '  export interface LayoutInfo {',
    '    name: string;',
    '    filePath: string;',
    '    isDefault: boolean;',
    '  }',
    ''
  ];

  const pageNames = pages.map(p => JSON.stringify(p.name));
  if (pageNames.length > 0) {
    lines.push('  export type RouteName =');
    lines.push(pageNames.map(n => `    | ${n}`).join('\n'));
    lines.push('  ;');
  } else {
    lines.push('  export type RouteName = string;');
  }

  lines.push('');

  const layoutNames = layouts.map(l => JSON.stringify(l.name));
  if (layoutNames.length > 0) {
    lines.push('  export type LayoutName =');
    lines.push(layoutNames.map(n => `    | ${n}`).join('\n'));
    lines.push('  ;');
  } else {
    lines.push('  export type LayoutName = "default" | string;');
  }

  lines.push('');

  const pageEntries = pages.map(
    p =>
      `    ${JSON.stringify(p.name)}: { name: ${JSON.stringify(p.name)}, path: ${JSON.stringify(p.path)}, filePath: ${JSON.stringify(p.fullPath)}, layout: ${JSON.stringify(p.layout)}, reuseTarget: ${JSON.stringify(p.reuseTarget)} }`
  );

  if (pageEntries.length > 0) {
    lines.push('  export const pages: {');
    lines.push(pageEntries.join(',\n'));
    lines.push('  };');
  } else {
    lines.push('  export const pages: Record<string, PageInfo>;');
  }

  lines.push('');

  const layoutEntries = layouts.map(
    l =>
      `    ${JSON.stringify(l.name)}: { name: ${JSON.stringify(l.name)}, filePath: ${JSON.stringify(l.fullPath)}, isDefault: ${l.isDefault} }`
  );

  if (layoutEntries.length > 0) {
    lines.push('  export const layouts: {');
    lines.push(layoutEntries.join(',\n'));
    lines.push('  };');
  } else {
    lines.push('  export const layouts: Record<string, LayoutInfo>;');
  }

  lines.push('}');

  return `${lines.join('\n')}\n`;
}
