/**
 * OpenAPI 类型生成
 *
 * 从 OpenAPI schema 生成 `paths` 类型声明文件(.ubean/openapi.d.ts),
 * 供 `createTypedClient<paths>` / `createTypedFlatClient<paths>` / `callTypedInternal<paths>` 消费。
 *
 * 底层使用 `openapi-typescript` 编译 schema 为 TypeScript 类型声明。
 */

import { writeFile, mkdir } from 'node:fs/promises';
import openapiTS, { astToString } from 'openapi-typescript';
import { join } from 'pathe';

export interface GenerateOpenApiTypesOptions {
  /** 输出目录(如 .ubean) */
  outDir: string;
  /** 输出文件名,默认 `openapi.d.ts` */
  fileName?: string;
}

/**
 * 从 OpenAPI schema 对象生成 paths 类型声明文件。
 *
 * @param schema - OpenAPI 3.x schema 对象(通常从 `/_openapi.json` 获取)
 * @param options - 输出选项
 * @returns 生成的文件绝对路径
 *
 * @example
 * ```typescript
 * import { generateOpenApiTypes } from 'ubean/core/codegen';
 *
 * const schema = await fetch('http://localhost:3000/_openapi.json').then(r => r.json());
 * await generateOpenApiTypes(schema, { outDir: '.ubean' });
 * // → 生成 .ubean/openapi.d.ts
 * ```
 */
export async function generateOpenApiTypes(schema: any, options: GenerateOpenApiTypesOptions): Promise<string> {
  const { outDir, fileName = 'openapi.d.ts' } = options;

  await mkdir(outDir, { recursive: true });

  // 用 openapi-typescript 编译 schema 为 AST
  const ast = await openapiTS(schema);
  const typesContent = astToString(ast);

  const header = [
    '// Auto-generated by ubean - do not edit manually',
    '/* eslint-disable */',
    '/* @ts-nocheck */',
    '',
    ''
  ].join('\n');

  const content = `${header + typesContent}\n`;
  const filePath = join(outDir, fileName);
  await writeFile(filePath, content, 'utf-8');

  return filePath;
}

/**
 * 从 dev server 的 `/_openapi.json` 路由获取 schema 并生成类型声明文件。
 *
 * @param baseUrl - dev server 的 base URL(如 `http://localhost:3000`)
 * @param options - 输出选项
 * @returns 生成的文件绝对路径
 *
 * @example
 * ```typescript
 * import { generateOpenApiTypesFromServer } from 'ubean/core/codegen';
 *
 * await generateOpenApiTypesFromServer('http://localhost:3000', { outDir: '.ubean' });
 * ```
 */
export async function generateOpenApiTypesFromServer(
  baseUrl: string,
  options: GenerateOpenApiTypesOptions
): Promise<string> {
  const url = `${baseUrl.replace(/\/$/, '')}/_openapi.json`;
  const response = await fetch(url);

  if (!response.ok) {
    throw new Error(
      `[openapi-types] Failed to fetch OpenAPI schema from ${url}: ${response.status} ${response.statusText}`
    );
  }

  const schema = (await response.json()) as object;
  return generateOpenApiTypes(schema, options);
}
