/**
 * OpenAPI 类型生成
 *
 * 从 OpenAPI schema 生成 `paths` 类型声明文件(.ubean/openapi.d.ts),
 * 供 `createTypedClient<paths>` / `createTypedFlatClient<paths>` / `callTypedInternal<paths>` 消费。
 *
 * 底层使用 `openapi-typescript` 编译 schema 为 TypeScript 类型声明。
 */

import { writeFile, mkdir } from 'node:fs/promises';
import openapiTS, { astToString } from 'openapi-typescript';
import { join } from 'pathe';

export interface GenerateOpenApiTypesOptions {
  /** 输出目录(如 .ubean) */
  outDir: string;
  /** 输出文件名,默认 `openapi.d.ts` */
  fileName?: string;
}

/**
 * 从 OpenAPI schema 对象生成 paths 类型声明文件。
 */
export async function generateOpenApiTypes(schema: unknown, options: GenerateOpenApiTypesOptions): Promise<string> {
  const { outDir, fileName = 'openapi.d.ts' } = options;

  await mkdir(outDir, { recursive: true });

  // 用 openapi-typescript 编译 schema 为 AST
  const ast = await openapiTS(schema as any);
  const typesContent = astToString(ast);

  const header = [
    '// Auto-generated by ubean - do not edit manually',
    '/* eslint-disable */',
    '/* @ts-nocheck */',
    '',
    ''
  ].join('\n');

  const content = `${header + typesContent}\n`;
  const filePath = join(outDir, fileName);
  await writeFile(filePath, content, 'utf-8');

  return filePath;
}

/**
 * 从 dev server 的 `/_openapi.json` 路由获取 schema 并生成类型声明文件。
 *
 * SSG / SPA 等无后端模式访问 `/_openapi.json` 时,dev server 会以 200 返回
 * HTML(页面 fallback)而非 JSON。此时跳过生成并返回 `null`,避免抛出
 * `Unexpected token '<'` 之类的误导性错误。
 */
export async function generateOpenApiTypesFromServer(
  baseUrl: string,
  options: GenerateOpenApiTypesOptions
): Promise<string | null> {
  const url = `${baseUrl.replace(/\/$/, '')}/_openapi.json`;
  const response = await fetch(url);

  if (!response.ok) {
    throw new Error(
      `[openapi-types] Failed to fetch OpenAPI schema from ${url}: ${response.status} ${response.statusText}`
    );
  }

  // 无后端模式会返回 HTML 而非 JSON,直接跳过、不报错
  const contentType = response.headers.get('content-type') || '';
  if (!contentType.includes('json')) {
    return null;
  }

  const schema = (await response.json()) as object;
  return generateOpenApiTypes(schema, options);
}
