import { mkdir, readFile, writeFile } from 'node:fs/promises';
import type { ScanResult, ScannedLocale } from '@ubean/scan';
import { join } from 'pathe';

export interface I18nTypesOptions {
  outDir: string;
  fileName?: string;
  defaultLocale?: string;
}

function isIdent(key: string): boolean {
  return /^[A-Za-z_$][\w$]*$/.test(key);
}

/** Convert a JSON message tree into a TypeScript object type body. */
export function messagesToTsType(value: unknown, indent = 1): string {
  if (value === null || typeof value !== 'object' || Array.isArray(value)) {
    return 'string';
  }
  const obj = value as Record<string, unknown>;
  const keys = Object.keys(obj);
  if (keys.length === 0) return 'Record<string, never>';
  const pad = '  '.repeat(indent);
  const inner = keys
    .map(k => {
      const key = isIdent(k) ? k : JSON.stringify(k);
      return `${pad}${key}: ${messagesToTsType(obj[k], indent + 1)};`;
    })
    .join('\n');
  return `{\n${inner}\n${'  '.repeat(indent - 1)}}`;
}

function unwrapMessages(raw: unknown): Record<string, unknown> | null {
  if (!raw || typeof raw !== 'object' || Array.isArray(raw)) return null;
  const obj = raw as Record<string, unknown>;
  const hasMeta =
    typeof obj.name === 'string' || obj.dir === 'ltr' || obj.dir === 'rtl' || typeof obj.isDefault === 'boolean';
  if (hasMeta && obj.messages && typeof obj.messages === 'object' && obj.messages !== null) {
    return obj.messages as Record<string, unknown>;
  }
  return obj;
}

function pickDefaultLocaleFile(locales: ScannedLocale[], defaultLocale?: string): ScannedLocale | undefined {
  const jsonFiles = locales.filter(l => {
    const lower = l.fullPath.toLowerCase();
    return (lower.endsWith('.json') || lower.endsWith('.json5')) && !l.namespace;
  });
  if (jsonFiles.length === 0) return undefined;
  if (defaultLocale) {
    const match = jsonFiles.find(l => l.code === defaultLocale);
    if (match) return match;
  }
  return jsonFiles.find(l => l.isDefault) || jsonFiles[0];
}

/**
 * Generate `.ubean/i18n.d.ts` augmenting vue-i18n `DefineLocaleMessage`
 * from the default locale JSON. Users can also hand-write the same
 * module augmentation if they prefer.
 */
export async function generateI18nTypes(result: ScanResult, options: I18nTypesOptions): Promise<string | null> {
  const { outDir, fileName = 'i18n.d.ts', defaultLocale } = options;
  const source = pickDefaultLocaleFile(result.locales || [], defaultLocale);
  if (!source) return null;

  let raw: unknown;
  try {
    const text = await readFile(source.fullPath, 'utf8');
    raw = JSON.parse(text);
  } catch {
    return null;
  }

  const messages = unwrapMessages(raw);
  if (!messages) return null;

  const typeBody = messagesToTsType(messages, 2);
  const contents = `// Auto-generated by ubean from ${source.relativePath} — do not edit manually
// Typed \`t('key')\` via vue-i18n \`DefineLocaleMessage\`.
// Override by adding your own \`declare module 'vue-i18n'\` in src/.
/* eslint-disable */
export {};

declare module 'vue-i18n' {
  export interface DefineLocaleMessage ${typeBody}
}
`;

  await mkdir(outDir, { recursive: true });
  const outPath = join(outDir, fileName);
  await writeFile(outPath, contents, 'utf8');
  return outPath;
}
