import { writeFile, mkdir } from 'node:fs/promises';
import type { ScanResult, ScannedApiRoute } from '@ubean/scan';
import { join, relative, isAbsolute } from 'pathe';

export interface RouteTypesOptions {
  /** Project root directory (absolute). Used to compute portable relative `filePath` values. */
  cwd: string;
  outDir: string;
  fileName?: string;
}

/**
 * Compute a portable file path for a scanned route.
 *
 * - If `fullPath` is under `cwd`, returns a POSIX-style project-relative path
 *   (e.g. `src/routes/api/users/[id].ts`). This keeps generated `.d.ts` files
 *   portable across machines and free of leaked absolute paths.
 * - Otherwise, falls back to the raw `fullPath` (already non-sensitive for
 *   non-local sources).
 */
function toPortableFilePath(route: ScannedApiRoute, cwd: string): string {
  const rel = isAbsolute(route.fullPath) ? relative(cwd, route.fullPath) : route.fullPath;
  return rel.replace(/\\/g, '/');
}

export async function generateRouteTypes(result: ScanResult, options: RouteTypesOptions): Promise<string> {
  const { cwd, outDir, fileName = 'routes.d.ts' } = options;
  await mkdir(outDir, { recursive: true });

  const apiRoutes = result.apiRoutes;

  const lines: string[] = [
    '// Auto-generated by ubean - do not edit manually',
    '/* eslint-disable */',
    '// @ts-nocheck',
    '',
    'declare module "ubean:routes" {',
    '  export interface ApiRoute {',
    '    method: string;',
    '    path: string;',
    '    filePath: string;',
    '    meta?: Record<string, unknown>;',
    '  }',
    ''
  ];

  // ApiRouteMap: path → method → { filePath }
  //
  // Design rationale:
  //   - Keyed by URL path (not `"METHOD path"`) so consumers can look up the
  //     supported methods for a given path in O(1) via `ApiRouteMap['/users']`.
  //   - Method-nested so each (path, method) pair carries its own `filePath`,
  //     preserving per-method source location (reuse routes can map different
  //     methods of the same path to different files).
  //   - `filePath` is project-relative (computed via `toPortableFilePath`)
  //     to avoid leaking absolute filesystem paths into generated artifacts.
  if (apiRoutes.length > 0) {
    // Group routes by path, preserving first-seen order for deterministic output.
    const groups = new Map<string, ScannedApiRoute[]>();
    for (const r of apiRoutes) {
      const list = groups.get(r.route);
      if (list) {
        list.push(r);
      } else {
        groups.set(r.route, [r]);
      }
    }

    const entries: string[] = [];
    for (const [path, routes] of groups) {
      const methodEntries = routes
        .map(r => {
          const method = (r.method || 'ALL').toUpperCase();
          const filePath = toPortableFilePath(r, cwd);
          return `      ${method}: { filePath: ${JSON.stringify(filePath)} }`;
        })
        .join(';\n');
      entries.push(`    ${JSON.stringify(path)}: {\n${methodEntries}\n    }`);
    }

    lines.push('  export type ApiRouteMap = {');
    lines.push(`${entries.join(';\n')};`);
    lines.push('  };');
  } else {
    lines.push('  export type ApiRouteMap = {};');
  }

  lines.push('');

  // Derive ApiRoutePath from ApiRouteMap keys when possible — single source
  // of truth, avoids drift between the map and the union.
  if (apiRoutes.length > 0) {
    lines.push('  export type ApiRoutePath = keyof ApiRouteMap;');
  } else {
    lines.push('  export type ApiRoutePath = string;');
  }

  lines.push('');

  const routeMethods = [...new Set(apiRoutes.map(r => r.method?.toUpperCase()).filter(Boolean))].sort();
  if (routeMethods.length > 0) {
    lines.push('  export type ApiMethod =');
    lines.push(routeMethods.map(m => `    | ${JSON.stringify(m)}`).join('\n'));
    lines.push('  ;');
  } else {
    lines.push('  export type ApiMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE" | "OPTIONS" | "HEAD";');
  }

  lines.push('');
  lines.push('  export const routes: ApiRoute[];');
  lines.push('  export const middlewares: { filePath: string; order: number; global: boolean }[];');
  lines.push('}');

  const content = `${lines.join('\n')}\n`;
  const filePath = join(outDir, fileName);
  await writeFile(filePath, content, 'utf-8');

  return filePath;
}

export interface PageTypesOptions {
  outDir: string;
  fileName?: string;
}

export async function generatePageTypes(result: ScanResult, options: PageTypesOptions): Promise<string> {
  const { outDir, fileName = 'pages.d.ts' } = options;
  await mkdir(outDir, { recursive: true });

  const pages = result.pages;
  const layouts = result.layouts;

  const lines: string[] = [
    '// Auto-generated by ubean - do not edit manually',
    '/* eslint-disable */',
    '// @ts-nocheck',
    '',
    'declare module "ubean:pages" {',
    '  export interface PageInfo {',
    '    name: string;',
    '    path: string;',
    '    filePath: string;',
    '    layout?: string;',
    '    reuseTarget?: string;',
    '  }',
    '',
    '  export interface LayoutInfo {',
    '    name: string;',
    '    filePath: string;',
    '    isDefault: boolean;',
    '  }',
    ''
  ];

  const pageNames = pages.map(p => JSON.stringify(p.name));
  if (pageNames.length > 0) {
    lines.push('  export type RouteName =');
    lines.push(pageNames.map(n => `    | ${n}`).join('\n'));
    lines.push('  ;');
  } else {
    lines.push('  export type RouteName = string;');
  }

  lines.push('');

  const layoutNames = layouts.map(l => JSON.stringify(l.name));
  if (layoutNames.length > 0) {
    lines.push('  export type LayoutName =');
    lines.push(layoutNames.map(n => `    | ${n}`).join('\n'));
    lines.push('  ;');
  } else {
    lines.push('  export type LayoutName = string;');
  }

  lines.push('');

  // Runtime values come from the virtual module (`ubean:pages`); this `.d.ts`
  // only provides type information. Using `Record<RouteName, PageInfo>` keeps
  // the declaration concise and avoids leaking absolute paths / verbose
  // literal object types into the generated file. Consumers still get full
  // type safety: `pages['SomePage'].filePath` is typed as `string`.
  lines.push('  export const pages: Record<RouteName, PageInfo>;');
  lines.push('  export const layouts: Record<LayoutName, LayoutInfo>;');

  lines.push('}');

  const content = `${lines.join('\n')}\n`;
  const filePath = join(outDir, fileName);
  await writeFile(filePath, content, 'utf-8');

  return filePath;
}
