import { existsSync } from 'node:fs';
import { mkdir, writeFile, rm, cp, readFile } from 'node:fs/promises';
import { build as viteBuild } from 'vite';
import type { Plugin as VitePlugin } from 'vite';
import vue from '@vitejs/plugin-vue';
import { useVirtualRegistry } from '@ubean/build-core';
import { getColorModeScript, resolveColorModeConfig } from '@ubean/client';
import type { ResolvedConfig } from '@ubean/config';
import { ubeanIslandsPlugin } from '@ubean/islands/vite';
import { getLogger } from '@ubean/logger';
import { resolveModules } from '@ubean/modules';
import type { Preset } from '@ubean/preset';
import type { ScanResult } from '@ubean/scan';
import { findUserViteConfig } from '@ubean/shared/node';
import {
  ubeanVite,
  VUE_PLUGIN_INCLUDE,
  createVuePagesVirtualModule,
  createVueAppEntryVirtualModule,
  createServerEntryVirtualModule,
  createClientEntryVirtualModule
} from '@ubean/vite';
import { join, resolve, relative } from 'pathe';
import { localeVueParamFromI18n, serializeI18nConfig } from './i18n-config';
import {
  createRoutingVirtualModule,
  createPagesVirtualModule,
  createMetaVirtualModule,
  createAppVirtualModule,
  createLocalesVirtualModule
} from './virtual-modules';
import { ubeanPlugin } from './vite';

const logger = getLogger('build');

export interface BuildOptions {
  cwd: string;
  config: ResolvedConfig;
  preset: Preset;
  scanResult: ScanResult;
  minify?: boolean;
  sourcemap?: boolean;
}

export interface BuildManifest {
  assets: Array<{
    file: string;
    src?: string;
    isEntry?: boolean;
    css?: string[];
  }>;
  entry: string;
  clientDir: string;
  serverDir: string;
  preset: string;
}

function getOutDirs(cwd: string, outputDir: string) {
  const outputRoot = resolve(cwd, outputDir);
  return {
    root: outputRoot,
    public: join(outputRoot, 'public'),
    server: join(outputRoot, 'server'),
    assets: join(outputRoot, 'public', 'assets'),
    virtual: join(cwd, '.ubean', 'virtual')
  };
}

function toVitePath(p: string): string {
  return p.replace(/\\/g, '/');
}

async function generateVirtualModulesToDisk(
  cwd: string,
  config: ResolvedConfig,
  scanResult: ScanResult,
  virtualDir: string
) {
  const mode = config.mode;
  const ssrEnabled = (mode === 'fullstack' && config.ssr.enabled) || mode === 'ssg';
  const hasPages = mode !== 'backend';
  const hasServer = mode !== 'spa';

  await mkdir(virtualDir, { recursive: true });
  const registry = useVirtualRegistry();
  registry.clear();

  const srcDirAbs = resolve(cwd, config.srcDir);
  const viteSrcDir = toVitePath(relative(cwd, srcDirAbs));
  const viteSrcPrefix = viteSrcDir ? `/${viteSrcDir}` : '';

  registry.register(
    createRoutingVirtualModule(
      scanResult.apiRoutes.map(r => ({
        method: r.method?.toUpperCase() || 'ALL',
        path: r.route,
        id: `${r.method}:${r.route}`,
        filePath: r.fullPath
      })),
      scanResult.middlewares.map(m => ({
        path: '/**',
        filePath: m.fullPath,
        order: m.order,
        global: m.global
      })),
      cwd
    )
  );

  if (hasPages) {
    registry.register(
      createPagesVirtualModule(
        scanResult.pages.map(p => ({
          name: p.name,
          path: p.route,
          filePath: p.fullPath,
          layout: p.layout,
          reuseTarget: p.reuseTarget
        })),
        scanResult.layouts.map(l => ({
          name: l.name,
          filePath: l.fullPath,
          isDefault: l.isDefault
        })),
        cwd
      )
    );

    registry.register(createMetaVirtualModule());
    registry.register(
      createVuePagesVirtualModule(
        scanResult.pages,
        scanResult.layouts,
        scanResult.notFoundPage,
        scanResult.loadingPage,
        scanResult.errorPage,
        localeVueParamFromI18n(config.i18n)
      )
    );
    registry.register(createVueAppEntryVirtualModule(scanResult.appEntry));
    registry.register(createClientEntryVirtualModule());
  }

  registry.register(
    createAppVirtualModule(
      scanResult.apiRoutes,
      scanResult.middlewares,
      hasPages ? scanResult.pages : [],
      viteSrcPrefix || '/'
    )
  );

  registry.register(
    createLocalesVirtualModule(
      scanResult.locales,
      scanResult.defaultLocale,
      viteSrcPrefix || '/',
      serializeI18nConfig(config.i18n)
    )
  );

  if (hasServer) {
    registry.register(createServerEntryVirtualModule(scanResult.serverEntry));
  }

  async function writeModule(id: string, filename: string, header = '// Auto-generated by ubean\n') {
    const mod = registry.getModules().find(m => m.id === id);
    const content = mod ? await mod.load() : '';
    await writeFile(join(virtualDir, filename), header + content, 'utf-8');
  }

  await writeModule('ubean:routes', 'routes.mjs');
  await writeModule('ubean:app-config', 'app-config.mjs');
  await writeModule('ubean:locales', 'locales.mjs');

  if (hasPages) {
    await writeModule('ubean:pages', 'pages.ts');
    await writeModule('ubean:meta', 'meta.mjs');
    await writeModule('virtual:ubean-pages', 'vue-pages.ts', '');
    await writeModule('virtual:ubean-app', 'vue-app.ts', '');
    await writeModule('virtual:ubean-client-entry', 'client-entry.mjs', '');
  }

  if (hasServer) {
    await writeModule('virtual:ubean-server', 'server-entry.ts', '');
  }

  // Islands registry stub for SSR build.
  // The real registry is populated by ubeanIslandsPlugin during the client
  // build (via transform/scan of SFCs with client:* directives). During SSR,
  // islands are rendered server-side — no client hydration — so an empty
  // stub suffices. This prevents the `virtual:ubean-islands-registry` import
  // (inside ubean/runtime/vue, pulled in via virtual:ubean-app) from leaking
  // unresolved into the SSR bundle when ubean is noExternal.
  await writeFile(join(virtualDir, 'islands-registry.ts'), 'export const islands = {};\n', 'utf-8');

  const pagesGlob = JSON.stringify(`${viteSrcPrefix}/pages/**/*.{vue,ts,tsx,js,jsx,md,mdx}`);
  const routesGlob = JSON.stringify(`${viteSrcPrefix}/routes/**/*.{ts,js,mjs}`);
  const middlewareGlob = JSON.stringify(`${viteSrcPrefix}/middleware/**/*.{ts,js,mjs}`);
  const layoutsGlob = JSON.stringify(`${viteSrcPrefix}/layouts/**/*.{vue,ts}`);
  // Point publicDir to the build output (not the source public/) so preview
  // serves the compiled client assets and copied static files.
  const outputDir = config.build.outputDir || 'dist';
  const publicDir = toVitePath(resolve(cwd, outputDir, 'public'));

  // Serialize scanned route/middleware/page/layout metadata so the production
  // server entry can pass it to createUbeanApp. registerRoutes() iterates over
  // these arrays (not the loaders) to know which routes/pages/middleware to
  // register — without them every request falls through to the 404 handler.
  const routesJson = JSON.stringify(
    scanResult.apiRoutes.map(r => ({
      relativePath: r.relativePath,
      route: r.route,
      method: r.method,
      fileMeta: r.fileMeta
    }))
  );
  const middlewareJson = JSON.stringify(
    scanResult.middlewares.map(m => ({
      relativePath: m.relativePath,
      order: m.order,
      global: m.global
    }))
  );
  const pagesJson = JSON.stringify(
    scanResult.pages.map(p => ({
      relativePath: p.relativePath,
      name: p.name,
      route: p.route,
      layout: p.layout,
      reuseTarget: p.reuseTarget,
      isReuse: p.isReuse,
      pageMeta: p.pageMeta
    }))
  );
  const layoutsJson = JSON.stringify(
    scanResult.layouts.map(l => ({
      name: l.name,
      relativePath: l.relativePath,
      isDefault: l.isDefault
    }))
  );

  // Serialize the auto-detected 404 page metadata so the production server
  // entry can pass it to createUbeanApp for the Hono catch-all handler.
  // Only the fields consumed by router.ts are serialized (layout + head).
  const notFoundPageJson = JSON.stringify(
    scanResult.notFoundPage
      ? {
          relativePath: scanResult.notFoundPage.relativePath,
          name: scanResult.notFoundPage.name,
          route: scanResult.notFoundPage.route,
          layout: scanResult.notFoundPage.layout,
          pageMeta: scanResult.notFoundPage.pageMeta
        }
      : null
  );

  // Pre-render the no-FOUC color-mode script at build time so the SSG/prerender
  // path (which bypasses Vite's `transformIndexHtml`) can inject it into every
  // HTML response. Dev mode is handled by `transformIndexHtml` in the vite plugin.
  const colorModeScript =
    config.colorMode !== false ? getColorModeScript(resolveColorModeConfig(config.colorMode)) : '';

  const rendererImport = ssrEnabled ? `import { createVueRenderer } from 'ubean/vue-ssr';` : '';
  const rendererSetup = ssrEnabled
    ? `
// --- SSR renderer setup ---
const _defaultLayout = _layouts.find(l => l.isDefault)?.name || null;

const _rendererRoutes = _pages.map(p => {
  // For reuse routes, load the target page's module (the .reuse.ts file
  // only contains definePage metadata, not a Vue component).
  const _targetPage = p.isReuse && p.reuseTarget ? _pages.find(tp => tp.name === p.reuseTarget) : undefined;
  const _loaderKey = _targetPage?.relativePath || p.relativePath;
  return {
    path: p.route.replace(/\\*\\*:(\\w[\\w-]*)/g, ':$1(.*)*'),
    name: p.name,
    component: async () => {
      const loader = pageLoaders[_loaderKey];
      if (!loader) throw new Error('Page loader not found: ' + _loaderKey);
      const mod = await loader();
      return mod.default || mod;
    },
    meta: {
      layout: p.layout === false ? false : p.layout || _defaultLayout,
      pageName: p.name,
      cache: p.cache === true ? true : undefined
    }
  };
});

const _layoutMap = new Map();
for (const l of _layouts) {
  _layoutMap.set(l.name, l.relativePath);
}

const _pageRenderer = createVueRenderer({
  routes: _rendererRoutes,
  async resolveLayoutComponent(name) {
    if (name === false || name == null) return null;
    const relPath = _layoutMap.get(name);
    if (!relPath) return null;
    const loader = layoutLoaders[relPath];
    if (!loader) return null;
    const mod = await loader();
    return mod.default || mod;
  },
  defaultLayout: _defaultLayout,
  resolveAppConfig: () => _resolveAppConfig('server')
});
`
    : `
// --- SSR disabled (mode=${mode}, ssr=${config.ssr.enabled}) ---
// pageRenderer is null; page requests fall back to a client-only HTML shell.
const _pageRenderer = null;`;
  if (hasServer) {
    const serverEntry = `// Auto-generated server entry
import { createUbeanApp, applyServerConfig } from 'ubean/runtime/app';
import 'ubean:locales';
${rendererImport}
import { resolveAppConfig as _resolveAppConfig } from 'virtual:ubean-app';
import { resolveServerConfig as _resolveServerConfig } from 'virtual:ubean-server';
import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

export { createUbeanApp };

const routeModules = import.meta.glob(${routesGlob}, { eager: false });
const middlewareModules = import.meta.glob(${middlewareGlob}, { eager: false });
const pageModules = import.meta.glob(${pagesGlob}, { eager: false });
const layoutModules = import.meta.glob(${layoutsGlob}, { eager: false });

const _srcPrefix = ${JSON.stringify(viteSrcPrefix)};
function normalizeKey(p) {
  const prefixes = ['/routes/', '/middleware/', '/pages/', '/layouts/'];
  for (const prefix of prefixes) {
    const fullPrefix = _srcPrefix + prefix;
    if (p.includes(fullPrefix)) {
      const idx = p.indexOf(fullPrefix);
      return p.slice(idx + fullPrefix.length);
    }
  }
  return p;
}

export const routeLoaders = {};
for (const [key, loader] of Object.entries(routeModules)) {
  routeLoaders[normalizeKey(key)] = loader;
}

export const middlewareLoaders = {};
for (const [key, loader] of Object.entries(middlewareModules)) {
  middlewareLoaders[normalizeKey(key)] = loader;
}

export const pageLoaders = {};
for (const [key, loader] of Object.entries(pageModules)) {
  pageLoaders[normalizeKey(key)] = loader;
}

const layoutLoaders = {};
for (const [key, loader] of Object.entries(layoutModules)) {
  layoutLoaders[normalizeKey(key)] = loader;
}

const _routes = ${routesJson};
const _middleware = ${middlewareJson};
const _pages = ${pagesJson};
const _layouts = ${layoutsJson};
const _notFoundPage = ${notFoundPageJson};
${rendererSetup}
// --- Client asset tags from Vite manifest ---
const __dirname = dirname(fileURLToPath(import.meta.url));
let _assetTags = { css: '', preloads: '', body: '', favicon: ${JSON.stringify(config.favicon)} };
try {
  const manifestPath = join(__dirname, '..', 'public', '.vite', 'manifest.json');
  const manifest = JSON.parse(readFileSync(manifestPath, 'utf-8'));
  const entry = Object.values(manifest).find(m => m.isEntry);
  if (entry) {
    _assetTags.body = '<script type="module" src="/' + entry.file + '"></script>';
    if (Array.isArray(entry.css)) {
      _assetTags.css = entry.css.map(c => '<link rel="stylesheet" href="/' + c + '">').join('\\n');
    }
  }
} catch (e) {
  console.warn('[ubean] Failed to load client manifest:', e.message || e);
}

export async function createApp(options = {}) {
  const app = createUbeanApp({
    rootDir: ${JSON.stringify(cwd)},
    routes: _routes,
    middleware: _middleware,
    pages: _pages,
    layouts: _layouts,
    routeLoaders,
    middlewareLoaders,
    pageLoaders,
    pageRenderer: _pageRenderer,
    pageAssetTags: _assetTags,
    publicDir: ${JSON.stringify(publicDir)},
    i18nConfig: ${JSON.stringify(config.i18n)},
    ssrExclude: ${JSON.stringify(config.ssr?.exclude ?? [])},
    streaming: ${JSON.stringify(config.ssr?.streaming ?? false)},
    notFoundPage: _notFoundPage || undefined,
    colorModeScript: ${JSON.stringify(colorModeScript)},
    ...options
  });

  // Apply user's defineServer config (plugins, hooks, onAppCreate) before init
  const _serverConfig = _resolveServerConfig('prod');
  await applyServerConfig(app, _serverConfig);

  await app.init();

  // Call onServerReady after init completes
  if (_serverConfig.onServerReady) {
    await _serverConfig.onServerReady(app);
  }

  return app;
}

export default async function createFetchHandler() {
  const app = await createApp();
  return app.fetch;
}

export const handler = async (req, ctx) => {
  const app = await createApp();
  return app.fetch(req, ctx);
};
`;
    await writeFile(join(virtualDir, 'server-entry.mjs'), serverEntry, 'utf-8');
  }

  return virtualDir;
}

function getPresetBuildConfig(preset: Preset) {
  const presetName = preset.name;

  switch (presetName) {
    case 'node':
    case 'bun':
    case 'deno':
      return {
        format: 'esm' as const,
        target: 'node18',
        entryType: 'node' as const,
        external: ['hono', 'vue', 'vue/server-renderer', /^ubean(\/.*)?$/, /^node:/]
      };
    case 'cloudflare':
      return {
        format: 'esm' as const,
        target: 'es2022',
        entryType: 'worker' as const,
        external: ['hono', 'vue', 'vue/server-renderer', /^ubean(\/.*)?$/]
      };
    case 'standard':
    default:
      return {
        format: 'esm' as const,
        target: 'es2022',
        entryType: 'fetch' as const,
        external: ['hono', 'vue', 'vue/server-renderer', /^ubean(\/.*)?$/]
      };
  }
}

function generateNodeServerEntry(): string {
  return `// Auto-generated ubean Node.js server entry
import { createServer } from 'node:http';
import createFetchHandler from './entry.mjs';

const port = Number(process.env.PORT || 9527);
const host = process.env.HOST || '0.0.0.0';

async function main() {
  const fetch = await createFetchHandler();

  const server = createServer(async (req, res) => {
    try {
      const protocol = req.socket?.encrypted ? 'https' : 'http';
      const url = \`\${protocol}://\${req.headers.host || host}\${req.url || '/'}\`;
      const headers = new Headers();
      for (const [key, value] of Object.entries(req.headers)) {
        if (value) {
          if (Array.isArray(value)) {
            for (const v of value) headers.append(key, v);
          } else {
            headers.set(key, value);
          }
        }
      }
      const method = req.method || 'GET';
      const body = method === 'GET' || method === 'HEAD' ? undefined : req;
      const webReq = new Request(url, { method, headers, body, duplex: 'half' });
      const webRes = await fetch(webReq);

      res.statusCode = webRes.status;
      res.statusMessage = webRes.statusText;
      webRes.headers.forEach((value, key) => res.setHeader(key, value));

      if (webRes.body) {
        const reader = webRes.body.getReader();
        try {
          while (true) {
            const { done, value: chunk } = await reader.read();
            if (done) break;
            res.write(chunk);
          }
        } finally {
          reader.releaseLock();
        }
      }
      res.end();
    } catch (err) {
      if (!res.headersSent) {
        res.statusCode = 500;
        res.setHeader('Content-Type', 'text/plain');
      }
      res.end(err instanceof Error ? err.message : String(err));
    }
  });

  server.listen(port, host, () => {
    console.log(\`ubean server listening on http://\${host}:\${port}\`);
  });

  const shutdown = () => {
    server.close(() => process.exit(0));
  };
  process.on('SIGINT', shutdown);
  process.on('SIGTERM', shutdown);
}

main();
`.trim();
}

function generateStandardHandlerEntry(): string {
  return `// Auto-generated ubean standard fetch handler
import createFetchHandler from './entry.mjs';

const handlerPromise = createFetchHandler();
export default async function fetch(req, ctx) {
  const handler = await handlerPromise;
  return handler(req, ctx);
}
`.trim();
}

function generateCloudflareWorkerEntry(): string {
  return `// Auto-generated ubean Cloudflare Worker entry
import createFetchHandler from './entry.mjs';

const handlerPromise = createFetchHandler();
export default {
  async fetch(req, env, ctx) {
    const handler = await handlerPromise;
    return handler(req, { ...ctx, env });
  }
};
`.trim();
}

export async function buildProduction(options: BuildOptions): Promise<BuildManifest> {
  const { cwd, config, preset, scanResult, minify = true, sourcemap = false } = options;
  const outDirs = getOutDirs(cwd, config.build.outputDir);
  const srcDir = resolve(cwd, config.srcDir);

  const mode = config.mode;
  const ssrEnabled = (mode === 'fullstack' && config.ssr.enabled) || mode === 'ssg';
  const hasPages = mode !== 'backend';
  const hasServer = mode !== 'spa';

  logger.info(
    `Cleaning output directory... (mode=${mode}${mode === 'fullstack' ? `, ssr=${config.ssr.enabled}` : ''})`
  );
  if (existsSync(outDirs.root)) {
    await rm(outDirs.root, { recursive: true, force: true });
  }
  if (hasPages) {
    await mkdir(outDirs.public, { recursive: true });
  }
  if (hasServer) {
    await mkdir(outDirs.server, { recursive: true });
  }

  logger.info('Generating virtual modules...');
  await generateVirtualModulesToDisk(cwd, config, scanResult, outDirs.virtual);

  // 检测用户是否提供了 vite.config — 如有则由用户配置提供 ubeanPlugin()
  // (ubeanPlugin() 包含 ubeanCorePlugin + ubeanVite + ubeanIslandsPlugin)
  // 此处仅补充 vue 插件(用户容易遗漏 include/isCustomElement 配置),
  // ubeanVite/ubeanIslandsPlugin 由用户的 ubeanPlugin() 提供,避免重复注册。
  const userViteConfig = findUserViteConfig(cwd);

  const builtinPlugins: VitePlugin[] = [];
  if (hasPages) {
    builtinPlugins.push(
      vue({
        include: VUE_PLUGIN_INCLUDE,
        template: {
          compilerOptions: {
            isCustomElement: (tag: string) => tag.startsWith('ubean-')
          }
        }
      }) as unknown as VitePlugin
    );
  }
  if (!userViteConfig) {
    // 无用户 vite.config:由 builtin 提供全部 ubean 插件
    builtinPlugins.push(ubeanPlugin({ config }));
    if (hasPages) {
      builtinPlugins.push(...ubeanVite({ config }), ubeanIslandsPlugin());
    }
  }

  const { plugins } = await resolveModules({
    cwd,
    config,
    builtinPlugins
  });

  const presetBuildConfig = getPresetBuildConfig(preset);
  const virtualDir = outDirs.virtual;

  const commonResolve = {
    alias: {
      'virtual:ubean-pages': join(virtualDir, 'vue-pages.ts'),
      'virtual:ubean-app': join(virtualDir, 'vue-app.ts'),
      'virtual:ubean-server': join(virtualDir, 'server-entry.ts'),
      'virtual:ubean-client-entry': join(virtualDir, 'client-entry.mjs'),
      '#ubean-pages': join(virtualDir, 'vue-pages.ts'),
      '#ubean-app': join(virtualDir, 'vue-app.ts'),
      '#ubean-server': join(virtualDir, 'server-entry.ts'),
      '#ubean-client-entry': join(virtualDir, 'client-entry.mjs'),
      'ubean:pages': join(virtualDir, 'pages.ts'),
      'ubean:routes': join(virtualDir, 'routes.mjs'),
      'ubean:app-config': join(virtualDir, 'app-config.mjs'),
      'ubean:locales': join(virtualDir, 'locales.mjs'),
      'ubean:meta': join(virtualDir, 'meta.mjs')
    }
  };

  let clientManifest: Record<string, any> = {};
  if (hasPages) {
    logger.info('Building client bundle...');
    const clientEntryPath = join(srcDir, 'entry.client.ts');
    const clientInput = existsSync(clientEntryPath) ? clientEntryPath : join(virtualDir, 'client-entry.mjs');

    const htmlEntry = `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
  <title>Ubean App</title>
</head>
<body>
  <div id="app"></div>
  <script type="module" src="virtual:ubean-client-entry"></script>
</body>
</html>`;
    await writeFile(join(virtualDir, 'index.html'), htmlEntry, 'utf-8');

    await viteBuild({
      root: cwd,
      configFile: userViteConfig ?? false,
      mode: 'production',
      build: {
        outDir: outDirs.public,
        assetsDir: 'assets',
        minify: minify ? 'oxc' : false,
        sourcemap,
        manifest: true,
        ssrManifest: true,
        rollupOptions: {
          input: {
            app: clientInput
          },
          output: {
            entryFileNames: 'assets/[name]-[hash].js',
            chunkFileNames: 'assets/chunks/[name]-[hash].js',
            assetFileNames: 'assets/[name]-[hash].[ext]'
          }
        },
        emptyOutDir: false
      },
      plugins: [...plugins],
      resolve: commonResolve,
      optimizeDeps: {
        exclude: [
          'ubean',
          'virtual:ubean-pages',
          'virtual:ubean-app',
          'virtual:ubean-server',
          'virtual:ubean-client-entry',
          '#ubean-pages',
          '#ubean-app',
          '#ubean-server',
          '#ubean-client-entry'
        ]
      }
    });

    const manifestPath = join(outDirs.public, '.vite', 'manifest.json');
    if (existsSync(manifestPath)) {
      try {
        clientManifest = JSON.parse(await readFile(manifestPath, 'utf-8'));
      } catch {}
    }

    const publicDir = join(cwd, 'public');
    if (existsSync(publicDir)) {
      logger.info('Copying public assets...');
      await cp(publicDir, outDirs.public, { recursive: true });
    }
  }

  let serverEntry = '';
  if (hasServer) {
    logger.info(ssrEnabled ? 'Building SSR bundle...' : 'Building server bundle (SSR disabled)...');
    const serverEntryPath = join(virtualDir, 'server-entry.mjs');

    await viteBuild({
      root: cwd,
      configFile: userViteConfig ?? false,
      mode: 'production',
      ssr: {
        target: presetBuildConfig.target === 'node18' ? 'node' : 'webworker',
        // Bundle the ubean package so that virtual module imports inside it
        // (e.g. `virtual:ubean-islands-registry` in `ubean/runtime/vue`) are
        // resolved by Vite plugins rather than leaking as bare `virtual:`
        // imports that Node's ESM loader cannot resolve at prerender time.
        noExternal: ['ubean']
      },
      build: {
        outDir: outDirs.server,
        ssr: true,
        minify: false,
        sourcemap,
        rollupOptions: {
          input: serverEntryPath,
          // Remove the ubean pattern from external — it conflicts with
          // `ssr.noExternal: ['ubean']` above. Keeping it would externalize
          // ubean, causing Node to load it from node_modules where the
          // virtual module import is unresolved.
          external: presetBuildConfig.external.filter(e => !(e instanceof RegExp && e.source.startsWith('^ubean'))),
          output: {
            format: presetBuildConfig.format,
            entryFileNames: 'entry.mjs',
            chunkFileNames: 'chunks/[name]-[hash].mjs',
            inlineDynamicImports: presetBuildConfig.entryType === 'worker'
          }
        },
        emptyOutDir: false
      },
      plugins: [
        ...plugins,
        {
          // SSR stub for `virtual:ubean-islands-registry`.
          // The real registry is populated by ubeanIslandsPlugin during the
          // client build. During SSR, islands are rendered server-side (no
          // client hydration), so an empty stub suffices.
          name: 'ubean:islands-ssr-stub',
          enforce: 'pre',
          resolveId(id) {
            if (id === 'virtual:ubean-islands-registry') return '\0virtual:ubean-islands-registry';
            return undefined;
          },
          load(id) {
            if (id === '\0virtual:ubean-islands-registry') return 'export const islands = {};';
            return undefined;
          }
        }
      ],
      resolve: commonResolve
    });

    serverEntry = 'entry.mjs';

    if (presetBuildConfig.entryType === 'node') {
      await writeFile(join(outDirs.server, 'server.mjs'), generateNodeServerEntry(), 'utf-8');
      serverEntry = 'server.mjs';

      const pkgJson = {
        type: 'module',
        private: true,
        main: './server.mjs',
        dependencies: {
          hono: '^4.0.0'
        }
      };
      await writeFile(join(outDirs.server, 'package.json'), JSON.stringify(pkgJson, null, 2), 'utf-8');
    } else if (presetBuildConfig.entryType === 'worker') {
      await writeFile(join(outDirs.server, 'worker.mjs'), generateCloudflareWorkerEntry(), 'utf-8');
      serverEntry = 'worker.mjs';

      const wranglerToml = `
name = "ubean-app"
main = "./server/worker.mjs"
compatibility_date = "2024-01-01"
assets = { directory = "./public" }
`.trim();
      await writeFile(join(outDirs.root, 'wrangler.toml'), wranglerToml, 'utf-8');
    } else {
      await writeFile(join(outDirs.server, 'handler.mjs'), generateStandardHandlerEntry(), 'utf-8');
      serverEntry = 'handler.mjs';
    }
  }

  const assets: BuildManifest['assets'] = [];
  for (const [key, entry] of Object.entries(clientManifest)) {
    assets.push({
      file: entry.file,
      src: key,
      isEntry: entry.isEntry,
      css: entry.css
    });
  }

  const manifest: BuildManifest = {
    assets,
    entry: serverEntry,
    clientDir: hasPages ? relative(cwd, outDirs.public) : '',
    serverDir: hasServer ? relative(cwd, outDirs.server) : '',
    preset: preset.name || 'standard'
  };

  await writeFile(join(outDirs.root, 'manifest.json'), JSON.stringify(manifest, null, 2), 'utf-8');

  logger.info(`Build complete! Output: ${outDirs.root}`);
  if (hasPages) {
    logger.info(`  Client assets: ${outDirs.public}`);
  }
  if (hasServer) {
    logger.info(`  Server bundle: ${outDirs.server}`);
    logger.info(`  Entry: ${serverEntry}`);
  }

  return manifest;
}
