import type { ScannedPageRoute, ScannedLayout, ScannedAppEntry, ScannedServerEntry } from '@ubean/scan';
import { generatePagesModuleSource } from '@ubean/vue/vite';
import { getCssImports } from './registry';
import { defineVirtualModule } from './virtual-registry';

/**
 * 页面虚拟模块(`virtual:ubean-pages`)。
 *
 * 生成逻辑已沉淀到 `@ubean/vue/vite` 的 `generatePagesModuleSource`
 * (页面路由唯一所有者,与精简内核 `virtual:ubean-vue-routes` 共用同一
 * 生成器)。此处仅保留框架层的模块 ID 注册(`defineVirtualModule`)与
 * 兼容签名;route meta 相比旧版额外携带 `matchers` / `transition` /
 * `requiresAuth` / `head` / `definePage({ meta })` 透传字段(超集,
 * 使 `createMatcherGuard()` 与 SPA head guard 在框架模式下同样可用)。
 */
export function createVuePagesVirtualModule(
  pages: ScannedPageRoute[],
  layouts: ScannedLayout[],
  notFoundPage?: ScannedPageRoute,
  loadingPage?: ScannedPageRoute,
  errorPage?: ScannedPageRoute,
  localeVueParam?: string
) {
  return defineVirtualModule('virtual:ubean-pages', () =>
    generatePagesModuleSource({ pages, layouts, notFoundPage, loadingPage, errorPage }, { vueParam: localeVueParam })
  );
}

const EMPTY_APP_ENTRY: ScannedAppEntry = {
  shared: { exists: false },
  server: { exists: false },
  client: { exists: false }
};

export function createVueAppEntryVirtualModule(appEntry: ScannedAppEntry = EMPTY_APP_ENTRY) {
  return defineVirtualModule('virtual:ubean-app', () => {
    const hasSharedApp = appEntry.shared.exists;
    const hasServerApp = appEntry.server.exists;
    const hasClientApp = appEntry.client.exists;

    const sharedImport = hasSharedApp
      ? `import _sharedApp from ${JSON.stringify(appEntry.shared.fullPath)};`
      : 'const _sharedApp = null;';
    const serverImport = hasServerApp
      ? `import _serverApp from ${JSON.stringify(appEntry.server.fullPath)};`
      : 'const _serverApp = null;';
    const clientImport = hasClientApp
      ? `import _clientApp from ${JSON.stringify(appEntry.client.fullPath)};`
      : 'const _clientApp = null;';

    return `${`
// Auto-generated by ubean - do not edit
/* eslint-disable */
${sharedImport}
${serverImport}
${clientImport}

import {
  createUbeanClientApp,
  createUbeanSSRApp,
  usePage,
  useRouter,
  useHead,
  useSeoMeta,
  Link,
  Head,
  getInitialPageData,
  getInitialState,
  defineApp,
  applyAppConfig,
  createDefaultAppConfig,
  createClientHead,
  createServerHead,
  hydrateIslands,
  hasPendingIslands,
  scheduleIslandHydration,
  configureI18nRuntime
} from 'ubean/client';

import { i18nConfig as _i18nConfig, loadLocale as _loadLocale } from 'ubean:locales';

if (_i18nConfig && _i18nConfig.enabled !== false) {
  configureI18nRuntime({
    config: {
      defaultLocale: _i18nConfig.defaultLocale,
      locales: (_i18nConfig.locales || []).map(l => typeof l === 'string' ? l : l.code),
      strategy: _i18nConfig.strategy || 'prefix_except_default',
      fallbackLocale: _i18nConfig.fallbackLocale || _i18nConfig.defaultLocale,
      cookieName: (_i18nConfig.detectBrowserLanguage && _i18nConfig.detectBrowserLanguage.cookieName) || 'ubean_locale',
      baseUrl: _i18nConfig.baseUrl || '',
      vueI18n: _i18nConfig.vueI18n
    },
    loadLocale: _loadLocale,
    locales: (_i18nConfig.locales || []).map(l => typeof l === 'string' ? { code: l } : l)
  });
}

export {
  createUbeanClientApp,
  createUbeanSSRApp,
  usePage,
  useRouter,
  useHead,
  useSeoMeta,
  Link,
  Head,
  getInitialPageData,
  getInitialState,
  defineApp,
  applyAppConfig,
  createDefaultAppConfig
};

import {
  routes,
  resolvePageComponent,
  resolveLayoutComponent,
  defaultLayout,
  pageNames,
  layoutNames,
  resolveLoadingComponent,
  resolveErrorComponent,
  hasNotFoundPage,
  hasErrorPage
} from 'virtual:ubean-pages';

export {
  routes,
  resolvePageComponent,
  resolveLayoutComponent,
  defaultLayout,
  pageNames,
  layoutNames,
  resolveLoadingComponent,
  resolveErrorComponent,
  hasNotFoundPage,
  hasErrorPage
};

function _mergeAppConfig(base, ...configs) {
  const result = { ...base };
  for (const cfg of configs) {
    if (!cfg) continue;
    if (cfg.plugins) result.plugins = [...(result.plugins || []), ...cfg.plugins];
    if (cfg.globalComponents) result.globalComponents = { ...(result.globalComponents || {}), ...cfg.globalComponents };
    if (cfg.provides) result.provides = { ...(result.provides || {}), ...cfg.provides };
    if (cfg.head) result.head = { ...(result.head || {}), ...cfg.head };
    if (cfg.rootId) result.rootId = cfg.rootId;
    if (cfg.rootAttrs) result.rootAttrs = { ...(result.rootAttrs || {}), ...cfg.rootAttrs };
    if (cfg.onAppCreated) result.onAppCreated = cfg.onAppCreated;
    if (cfg.onClientReady) result.onClientReady = cfg.onClientReady;
    if (cfg.errorComponent) result.errorComponent = cfg.errorComponent;
    if (cfg.loadingComponent) result.loadingComponent = cfg.loadingComponent;
    if (cfg.viewTransitions !== undefined) result.viewTransitions = cfg.viewTransitions;
    if (cfg.serializeState) result.serializeState = cfg.serializeState;
    if (cfg.hydrateState) result.hydrateState = cfg.hydrateState;
  }
  // router.setup:累加语义 — shared 和 client/server 各自定义的 setup 都会执行
  // (顺序:shared 先,client/server 后)。这样 shared 可放通用守卫(如埋点),
  // client/server 可放环境专用守卫(如 SSR 鉴权)。
  const setups = [];
  for (const cfg of [base, ...configs]) {
    if (cfg?.router?.setup) setups.push(cfg.router.setup);
  }
  if (setups.length === 1) {
    result.router = { setup: setups[0] };
  } else if (setups.length > 1) {
    result.router = {
      setup: (router) => {
        for (const s of setups) s(router);
      }
    };
  }
  return result;
}

export function resolveAppConfig(mode) {
  const base = createDefaultAppConfig();
  if (!_sharedApp && !_serverApp && !_clientApp) return base;

  const sharedCfg = typeof _sharedApp === 'function' ? _sharedApp() : _sharedApp;
  const serverCfg = mode === 'server' && _serverApp ? (typeof _serverApp === 'function' ? _serverApp() : _serverApp) : null;
  const clientCfg = mode === 'client' && _clientApp ? (typeof _clientApp === 'function' ? _clientApp() : _clientApp) : null;

  const merged = _mergeAppConfig(base, sharedCfg, mode === 'server' ? serverCfg : clientCfg);

  // onAppCreated: shared config is the default; server/client-specific overrides it if present.
  if (sharedCfg?.onAppCreated) merged.onAppCreated = sharedCfg.onAppCreated;
  if (mode === 'client' && clientCfg?.onClientReady) merged.onClientReady = clientCfg.onClientReady;
  else if (mode === 'server' && serverCfg?.onAppCreated) merged.onAppCreated = serverCfg.onAppCreated;

  return merged;
}

export async function createApp() {
  const config = resolveAppConfig('client');
  const head = createClientHead();

  // Push global app head (from defineApp) as defaults before any page-level head.
  if (config.head) {
    const headInput = {};
    if (config.head.title) headInput.title = config.head.title;
    if (config.head.htmlAttrs) headInput.htmlAttrs = config.head.htmlAttrs;
    if (config.head.bodyAttrs) headInput.bodyAttrs = config.head.bodyAttrs;
    if (config.head.meta) headInput.meta = config.head.meta;
    if (config.head.link) headInput.link = config.head.link;
    if (config.head.script) headInput.script = config.head.script;
    head.push(headInput);
  }

  // Resolve the auto-detected loading/error components from pages/loading.vue
  // and pages/error.vue. These loaders return Promises (dynamic imports), so
  // they MUST be awaited — otherwise 'resolveComp' markRaw's the unresolved
  // Promise object and passes it to <Suspense>/<ErrorBoundary> as the
  // 'component' prop, causing "Hydration node mismatch: server <div> vs
  // client Symbol(v-fgt)" (rendering a Promise produces a fragment).
  // defineApp({ loadingComponent/errorComponent }) takes priority.
  const loadingComponent = config.loadingComponent || (await resolveLoadingComponent()) || undefined;
  const errorComponent = config.errorComponent || (await resolveErrorComponent()) || undefined;

  const initialPage = getInitialPageData();
  const instance = createUbeanClientApp({
    routes,
    resolveLayoutComponent,
    defaultLayout,
    head,
    viewTransitions: config.viewTransitions,
    initialPage: initialPage || undefined,
    hydrate: !!initialPage,
    routerSetup: config.router?.setup,
    loadingComponent,
    errorComponent
  });

  applyAppConfig(instance.app, config, 'client');

  if (config.onAppCreated) config.onAppCreated(instance.app);

  // SSR 状态水合:在 applyAppConfig(注册插件)之后、mount 之前调用。
  // getInitialState() 从 DOM 的 __UBEAN_STATE__ script 读取服务端
  // serializeState 产生的状态对象(如 Pinia 的 state)。
  // 必须在 mount 前执行,否则 store 已初始化为默认值,水合无效。
  if (config.hydrateState) {
    const state = getInitialState();
    config.hydrateState(instance.app, state);
  }

  const mountApp = () => {
    instance.app.mount('#' + (config.rootId || 'app'));
    if (config.onClientReady) {
      config.onClientReady(instance.app);
    }
    // Islands: first mount always waits two rAFs so Vue's patch finishes.
    // SPA afterEach waits one rAF, then skips the second when no pending islands.
    var appRoot = function () {
      return document.getElementById('app') || undefined;
    };
    var hydrateNow = function () {
      hydrateIslands({ appContext: instance.app, root: appRoot() });
    };
    var pendingIslands = function () {
      return hasPendingIslands(appRoot());
    };
    scheduleIslandHydration({
      requestAnimationFrame: requestAnimationFrame,
      hasPending: pendingIslands,
      hydrate: hydrateNow,
      forceDoubleFrame: true
    });
    instance.router.afterEach(function () {
      scheduleIslandHydration({
        requestAnimationFrame: requestAnimationFrame,
        hasPending: pendingIslands,
        hydrate: hydrateNow
      });
    });
  };

  // When hydrating SSR content, must wait for router to be ready before mounting,
  // otherwise RouterView has no matched route and causes hydration mismatch.
  if (initialPage) {
    instance.router.isReady().then(mountApp);
  } else {
    mountApp();
  }

  return instance;
}

export async function createSSRApp(initialPage) {
  const config = resolveAppConfig('server');
  const head = createServerHead();

  // SSR doesn't need Suspense fallback (server resolves async synchronously),
  // but we still pass it for consistency. Await the loaders so resolved
  // Component values (not Promises) are passed to createUbeanSSRApp.
  const loadingComponent = config.loadingComponent || (await resolveLoadingComponent()) || undefined;

  const errorComponent = config.errorComponent || (await resolveErrorComponent()) || undefined;

  const { app, router } = createUbeanSSRApp(initialPage, {
    routes,
    resolveLayoutComponent,
    defaultLayout,
    head,
    routerSetup: config.router?.setup,
    loadingComponent,
    errorComponent
  });

  applyAppConfig(app, config, 'server');

  if (config.onAppCreated) config.onAppCreated(app);

  return { app, router, head, config };
}

export const rootId = 'app';
`.trim()}\n`;
  });
}

export function createClientEntryVirtualModule() {
  return defineVirtualModule('virtual:ubean-client-entry', () => {
    const cssImports = getCssImports();
    const cssLines = cssImports.map((css: string) => `import ${JSON.stringify(css)};`).join('\n');
    return `${`
// Auto-generated by ubean client entry - do not edit
/* eslint-disable */
${cssLines}
import { createApp } from 'virtual:ubean-app';

createApp();
`.trim()}\n`;
  });
}

const EMPTY_SERVER_ENTRY: ScannedServerEntry = {
  shared: { exists: false },
  dev: { exists: false },
  prod: { exists: false }
};

export function createServerEntryVirtualModule(serverEntry: ScannedServerEntry = EMPTY_SERVER_ENTRY) {
  return defineVirtualModule('virtual:ubean-server', () => {
    const hasShared = serverEntry.shared.exists;
    const hasDev = serverEntry.dev.exists;
    const hasProd = serverEntry.prod.exists;

    const sharedImport = hasShared
      ? `import _sharedServer from ${JSON.stringify(serverEntry.shared.fullPath)};`
      : 'const _sharedServer = null;';
    const devImport = hasDev
      ? `import _devServer from ${JSON.stringify(serverEntry.dev.fullPath)};`
      : 'const _devServer = null;';
    const prodImport = hasProd
      ? `import _prodServer from ${JSON.stringify(serverEntry.prod.fullPath)};`
      : 'const _prodServer = null;';

    return `${`
// Auto-generated by ubean server entry - do not edit
/* eslint-disable */
${sharedImport}
${devImport}
${prodImport}

import {
  defineServer,
  createDefaultServerConfig,
  mergeServerConfigs
} from 'ubean/runtime/app';

export {
  defineServer,
  createDefaultServerConfig,
  mergeServerConfigs
};

/**
 * Resolve the user's server config for the given mode ('dev' | 'prod').
 * Merges shared config with mode-specific config. Returns an empty
 * config when no server entry file exists.
 */
export function resolveServerConfig(mode) {
  const base = createDefaultServerConfig();

  if (!_sharedServer && !_devServer && !_prodServer) return base;

  const sharedCfg = typeof _sharedServer === 'function' ? _sharedServer() : _sharedServer;
  const modeCfg = mode === 'dev'
    ? (typeof _devServer === 'function' ? _devServer() : _devServer)
    : (typeof _prodServer === 'function' ? _prodServer() : _prodServer);

  return mergeServerConfigs(base, sharedCfg, modeCfg);
}
`.trim()}\n`;
  });
}
