import type { ScanResult, ScannedPageRoute, ScannedLayout } from '../types';

/**
 * Options for the physical route file generator.
 *
 * The generator produces 3 files under `outDir`:
 *  - `routes.ts`         — flat route records (`RouteRecord[]`) with name/path/component/layout/meta
 *  - `imports.ts`        — lazy `views` and `layouts` records (for `import.meta.glob`-free consumption)
 *  - `typed-router.d.ts` — type definitions (`RouteKey`, `RoutePath`, `RouteLayoutKey`, `ReuseRouteKey`)
 *
 * The `vue-router` module augmentation (`RouteNamedMap`) is intentionally NOT
 * generated here — it is owned by `@ubean/runtime` to keep this package
 * decoupled from the Vue runtime (see T3-1).
 */
export interface GeneratorOptions {
  /** Project root directory (absolute). */
  cwd: string;
  /** Output directory for `routes.ts` / `imports.ts` (absolute or relative to `cwd`). */
  outDir: string;
  /** Path for `typed-router.d.ts` (absolute or relative to `cwd`). Default: `<outDir>/typed-router.d.ts`. */
  dtsPath?: string;
  /** Whether to generate `routes.ts`. Default: `true`. */
  generateRoutes?: boolean;
  /** Whether to generate `imports.ts`. Default: `true`. */
  generateImports?: boolean;
  /** Whether to generate `typed-router.d.ts`. Default: `true`. */
  generateDts?: boolean;
  /** Use lazy `() => import(...)` for views. Default: `true`. */
  routeLazy?: boolean | ((page: ScannedPageRoute) => boolean);
  /** Use lazy `() => import(...)` for layouts. Default: `true`. */
  layoutLazy?: boolean | ((layout: ScannedLayout) => boolean);
  /**
   * Compute extra `meta` for a route. The returned object is merged
   * on top of the page's existing `pageMeta.meta` (from `definePage` / frontmatter).
   * Return `null` to skip. Existing keys are NOT overwritten.
   */
  getRouteMeta?: (page: ScannedPageRoute) => Record<string, unknown> | null;
  /**
   * Compute the import specifier for a page file. Receives the absolute
   * `fullPath` of the page; should return a module specifier usable from
   * `imports.ts`. Defaults to a project-relative path prefixed with `@/`.
   */
  getImportPath?: (page: ScannedPageRoute) => string;
  /** Same as `getImportPath` but for layouts. */
  getLayoutImportPath?: (layout: ScannedLayout) => string;
  /**
   * Header comment prepended to every generated file. Default: a
   * `// @generated by ubean-routing — do not edit` notice with a timestamp.
   */
  headerComment?: string;
}

export interface GeneratorResult {
  routesPath?: string;
  importsPath?: string;
  dtsPath?: string;
  routeCount: number;
  layoutCount: number;
}

export const DEFAULT_HEADER_COMMENT =
  '// @generated by @ubean/routing/generator — do not edit manually.\n' +
  '// This file is regenerated on every dev start / build.';

export async function generateRouteFiles(scanResult: ScanResult, options: GeneratorOptions): Promise<GeneratorResult> {
  const gen = new RouteFileGenerator(options);
  return gen.generate(scanResult);
}

export class RouteFileGenerator {
  private readonly opts: Required<Omit<GeneratorOptions, 'getRouteMeta' | 'getImportPath' | 'getLayoutImportPath'>> &
    Pick<GeneratorOptions, 'getRouteMeta' | 'getImportPath' | 'getLayoutImportPath'>;

  constructor(options: GeneratorOptions) {
    const dtsPath = options.dtsPath ?? joinPosix(options.outDir, 'typed-router.d.ts');
    this.opts = {
      cwd: options.cwd,
      outDir: options.outDir,
      dtsPath,
      generateRoutes: options.generateRoutes ?? true,
      generateImports: options.generateImports ?? true,
      generateDts: options.generateDts ?? true,
      routeLazy: options.routeLazy ?? true,
      layoutLazy: options.layoutLazy ?? true,
      headerComment: options.headerComment ?? DEFAULT_HEADER_COMMENT,
      getRouteMeta: options.getRouteMeta,
      getImportPath: options.getImportPath,
      getLayoutImportPath: options.getLayoutImportPath
    } as RouteFileGenerator['opts'];
  }

  async generate(scanResult: ScanResult): Promise<GeneratorResult> {
    const { cwd, outDir, dtsPath, generateRoutes, generateImports, generateDts } = this.opts;

    const routesPath = generateRoutes ? joinPosix(outDir, 'routes.ts') : undefined;
    const importsPath = generateImports ? joinPosix(outDir, 'imports.ts') : undefined;
    const finalDtsPath = generateDts ? dtsPath : undefined;

    await Promise.all([
      routesPath ? writeFile(resolvePath(cwd, routesPath), this.renderRoutesFile(scanResult)) : null,
      importsPath ? writeFile(resolvePath(cwd, importsPath), this.renderImportsFile(scanResult)) : null,
      finalDtsPath ? writeFile(resolvePath(cwd, finalDtsPath), this.renderDtsFile(scanResult)) : null
    ]);

    return {
      routesPath,
      importsPath,
      dtsPath: finalDtsPath,
      routeCount: scanResult.pages.length,
      layoutCount: scanResult.layouts.length
    };
  }

  /* ----------------------------------------------------------------------- */
  /* routes.ts                                                               */
  /* ----------------------------------------------------------------------- */

  renderRoutesFile(scanResult: ScanResult): string {
    const header = this.opts.headerComment;
    const items = scanResult.pages.map(p => this.renderRouteRecord(p)).join(',\n');

    return `${header}

import type { RouteRecord } from './imports';

export const routes: RouteRecord[] = [
${items}
];
`;
  }

  private renderRouteRecord(page: ScannedPageRoute): string {
    const parts: string[] = [];
    parts.push(`  name: ${JSON.stringify(page.name)}`);
    parts.push(`  path: ${JSON.stringify(page.route)}`);

    const component = this.opts.getImportPath?.(page) ?? defaultPageImportPath(page, this.opts.cwd);
    parts.push(`  component: ${JSON.stringify(component)}`);

    if (page.layout !== undefined) {
      const layoutVal = page.layout === false ? 'false' : JSON.stringify(page.layout);
      parts.push(`  layout: ${layoutVal}`);
    }

    if (page.isReuse) {
      parts.push(`  reuse: true`);
    }

    const meta = this.computeMeta(page);
    if (meta && Object.keys(meta).length > 0) {
      parts.push(`  meta: ${JSON.stringify(meta)}`);
    }

    if (page.pageMeta?.cache === true) {
      parts.push(`  cache: true`);
    }

    if (page.pageMeta?.requiresAuth === true) {
      parts.push(`  requiresAuth: true`);
    }

    if (page.pageMeta?.middleware) {
      const mw = page.pageMeta.middleware;
      const mwVal = Array.isArray(mw) ? JSON.stringify(mw) : JSON.stringify(mw);
      parts.push(`  middleware: ${mwVal}`);
    }

    return `  {\n${parts.join(',\n')}\n  }`;
  }

  private computeMeta(page: ScannedPageRoute): Record<string, unknown> | null {
    const base = page.pageMeta?.meta ?? {};
    const extra = this.opts.getRouteMeta?.(page) ?? {};

    // Existing keys take precedence (do not overwrite definePage meta)
    const merged: Record<string, unknown> = { ...extra, ...base };
    return Object.keys(merged).length > 0 ? merged : null;
  }

  /* ----------------------------------------------------------------------- */
  /* imports.ts                                                              */
  /* ----------------------------------------------------------------------- */

  renderImportsFile(scanResult: ScanResult): string {
    const header = this.opts.headerComment;
    const layouts = scanResult.layouts.map(l => this.renderLayoutImport(l)).join(',\n');
    const views = scanResult.pages
      .filter(p => !p.isReuse)
      .map(p => this.renderViewImport(p))
      .join(',\n');

    const layoutType =
      scanResult.layouts.length > 0 ? `'${scanResult.layouts.map(l => l.name).join("' | '")}'` : 'string';
    const viewType = scanResult.pages.length > 0 ? `'${scanResult.pages.map(p => p.name).join("' | '")}'` : 'string';

    return `${header}

export type LayoutKey = ${layoutType};
export type RouteKey = ${viewType};

export type Lazy<T> = () => Promise<T>;
export type RawRouteComponent = import('vue').Component | Lazy<import('vue').Component>;

export interface RouteRecord {
  name: RouteKey;
  path: string;
  component: string;
  layout?: LayoutKey | false;
  reuse?: boolean;
  meta?: Record<string, unknown>;
  cache?: boolean;
  requiresAuth?: boolean;
  middleware?: string | string[];
}

export const layouts: Record<LayoutKey, RawRouteComponent> = {
${layouts}
};

export const views: Record<RouteKey, RawRouteComponent> = {
${views}
};
`;
  }

  private renderLayoutImport(layout: ScannedLayout): string {
    const importPath = this.opts.getLayoutImportPath?.(layout) ?? defaultLayoutImportPath(layout, this.opts.cwd);
    const lazy = typeof this.opts.layoutLazy === 'function' ? this.opts.layoutLazy(layout) : this.opts.layoutLazy;
    if (lazy) {
      return `  ${layout.name}: () => import(${JSON.stringify(importPath)})`;
    }
    const importName = `__layout_${layout.name}`;
    return `  ${layout.name}: ${importName}, // import ${importName} from ${JSON.stringify(importPath)}`;
  }

  private renderViewImport(page: ScannedPageRoute): string {
    const importPath = this.opts.getImportPath?.(page) ?? defaultPageImportPath(page, this.opts.cwd);
    const lazy = typeof this.opts.routeLazy === 'function' ? this.opts.routeLazy(page) : this.opts.routeLazy;
    if (lazy) {
      return `  ${page.name}: () => import(${JSON.stringify(importPath)})`;
    }
    return `  ${page.name}: ${page.name}, // import ${page.name} from ${JSON.stringify(importPath)}`;
  }

  /* ----------------------------------------------------------------------- */
  /* typed-router.d.ts                                                       */
  /* ----------------------------------------------------------------------- */

  renderDtsFile(scanResult: ScanResult): string {
    const header = this.opts.headerComment;

    const pathMapEntries =
      scanResult.pages.length > 0
        ? scanResult.pages.map(p => `    "${p.name}": "${p.route}";`).join('\n')
        : '    // (no pages scanned)';

    const reuseRoutes = scanResult.pages.filter(p => p.isReuse);
    const reuseKeys = reuseRoutes.length > 0 ? reuseRoutes.map(p => `"${p.name}"`).join(' | ') : 'never';

    const layoutKeyList =
      scanResult.layouts.length > 0 ? scanResult.layouts.map(l => `"${l.name}"`).join(' | ') : 'never';

    return `${header}

declare module '@ubean/routing' {
  /**
   * Route layout keys scanned from \`src/layouts/\`.
   */
  export type RouteLayoutKey = ${layoutKeyList};

  /**
   * Map of route name → route path, scanned from \`src/pages/\`.
   */
  export interface RoutePathMap {
${pathMapEntries}
  }

  /**
   * Route names (keys of {@link RoutePathMap}).
   */
  export type RouteKey = keyof RoutePathMap;

  /**
   * Route paths (values of {@link RoutePathMap}).
   */
  export type RoutePath = RoutePathMap[RouteKey];

  /**
   * Reuse route keys (pages using \`.reuse.vue\` suffix).
   */
  export type ReuseRouteKey = ${reuseKeys};
}

export type { RouteLayoutKey, RoutePathMap, RouteKey, RoutePath, ReuseRouteKey } from '@ubean/routing';
`;
  }
}

/* -------------------------------------------------------------------------- */
/* Helpers                                                                    */
/* -------------------------------------------------------------------------- */

function defaultPageImportPath(page: ScannedPageRoute, cwd: string): string {
  // Default: relative path from project root, prefixed with `@/`
  const rel = relativePosix(cwd, page.fullPath);
  const withoutExt = rel.replace(/\.(vue|tsx?|jsx?|mdx?)$/, '');
  return `@/${withoutExt}`;
}

function defaultLayoutImportPath(layout: ScannedLayout, cwd: string): string {
  const rel = relativePosix(cwd, layout.fullPath);
  const withoutExt = rel.replace(/\.(vue|tsx?|jsx?)$/, '');
  return `@/${withoutExt}`;
}

function joinPosix(...parts: string[]): string {
  return parts
    .map(p => p.replace(/\\/g, '/'))
    .join('/')
    .replace(/\/+/g, '/');
}

/**
 * 将 `cwd` 与 `target` 合并为最终写入路径。
 *
 * 与 `joinPosix` 不同,此函数会识别 `target` 是否为绝对路径:
 * - 如果 `target` 以 `/` 开头(POSIX 绝对路径)或盘符开头(Windows,如 `C:`),
 *   直接使用 `target`,忽略 `cwd`
 * - 否则,使用 `joinPosix(cwd, target)` 拼接
 *
 * 这是为了支持消费方(`@ubean/build`)传入 `path.resolve()` 计算出的绝对路径,
 * 避免出现 `<cwd>/<absolute-target>` 这种重复前缀的错误路径(参见
 * `maybeGenerateRouteFiles` 中 `resolve(config.rootDir, ...)` 的调用)。
 */
function resolvePath(cwd: string, target: string): string {
  const normalized = target.replace(/\\/g, '/');
  // POSIX 绝对路径(/...)或 Windows 绝对路径(C:\... / C:/...)
  if (normalized.startsWith('/') || /^[a-zA-Z]:[\\/]/.test(normalized)) {
    return normalized;
  }
  return joinPosix(cwd, normalized);
}

function relativePosix(from: string, to: string): string {
  // Lightweight posix `path.relative` without pulling in `pathe` here.
  const fromParts = resolvePosix(from).split('/').filter(Boolean);
  const toParts = resolvePosix(to).split('/').filter(Boolean);

  let i = 0;
  while (i < fromParts.length && i < toParts.length && fromParts[i] === toParts[i]) i++;

  const up = fromParts.slice(i).map(() => '..');
  const down = toParts.slice(i);
  return [...up, ...down].join('/') || '.';
}

function resolvePosix(p: string): string {
  if (p.startsWith('/')) return p.replace(/\\/g, '/');
  return p.replace(/\\/g, '/');
}

async function writeFile(path: string, content: string): Promise<void> {
  const { mkdir, writeFile: fsWriteFile } = await import('node:fs/promises');
  const { dirname } = await import('node:path');
  await mkdir(dirname(path), { recursive: true });
  await fsWriteFile(path, content, 'utf-8');
}
