import type { ScanResult, ScannedPageRoute, ScannedLayout } from '../types';

/**
 * Options for the physical route file generator.
 *
 * The generator produces 3 files under `outDir`:
 *  - `routes.ts`         — flat route records (`RouteRecord[]`) with name/path/component/layout/meta
 *  - `imports.ts`        — lazy `views` and `layouts` records (for `import.meta.glob`-free consumption)
 *  - `typed-router.d.ts` — type definitions:
 *     - `@ubean/routing` 模块增强:`RouteKey`、`RoutePath`、`RouteLayoutKey`、`ReuseRouteKey`、`RoutePathMap`
 *     - `vue-router/auto-routes` 模块增强:`RouteNamedMap`(name → `RouteRecordInfo<Name, Path, ParamsRaw, Params>`)
 *     - `vue-router` 模块增强:`TypesConfig.RouteNamedMap` 引用上面的 `RouteNamedMap`
 *
 * `RouteNamedMap` 让 `vue-router` 的 `useRoute<Name>(name)` 能根据路由名推断
 * `route.params` 的类型(动态路由 `:id` / `:id?` 自动类型化),无需用户手动断言。
 * 这与 elegant-router 的 `typed-router.d.ts` 行为对齐。
 */
export interface GeneratorOptions {
  /** Project root directory (absolute). */
  cwd: string;
  /**
   * Source directory (absolute, defaults to `<cwd>/src`).
   *
   * Used by the default `getImportPath` / `getLayoutImportPath` to compute
   * import specifiers relative to `srcDir` (the conventional target of the
   * `@/` path alias). When the alias differs, supply custom `getImportPath` /
   * `getLayoutImportPath` callbacks.
   */
  srcDir?: string;
  /** Output directory for `routes.ts` / `imports.ts` (absolute or relative to `cwd`). */
  outDir: string;
  /** Path for `typed-router.d.ts` (absolute or relative to `cwd`). Default: `<outDir>/typed-router.d.ts`. */
  dtsPath?: string;
  /** Whether to generate `routes.ts`. Default: `true`. */
  generateRoutes?: boolean;
  /** Whether to generate `imports.ts`. Default: `true`. */
  generateImports?: boolean;
  /** Whether to generate `typed-router.d.ts`. Default: `true`. */
  generateDts?: boolean;
  /** Use lazy `() => import(...)` for views. Default: `true`. */
  routeLazy?: boolean | ((page: ScannedPageRoute) => boolean);
  /** Use lazy `() => import(...)` for layouts. Default: `true`. */
  layoutLazy?: boolean | ((layout: ScannedLayout) => boolean);
  /**
   * Compute extra `meta` for a route. The returned object is merged
   * on top of the page's existing `pageMeta.meta` (from `definePage` / frontmatter).
   * Return `null` to skip. Existing keys are NOT overwritten.
   */
  getRouteMeta?: (page: ScannedPageRoute) => Record<string, unknown> | null;
  /**
   * Compute the import specifier for a page file. Receives the absolute
   * `fullPath` of the page; should return a module specifier usable from
   * `imports.ts`. Defaults to a `srcDir`-relative path prefixed with `@/`
   * (e.g. `@/pages/about.vue`), matching the common `@/` → `src/` alias.
   */
  getImportPath?: (page: ScannedPageRoute) => string;
  /** Same as `getImportPath` but for layouts. */
  getLayoutImportPath?: (layout: ScannedLayout) => string;
  /**
   * Header comment prepended to every generated file. Default: a
   * `// @generated by ubean-routing — do not edit` notice with a timestamp.
   */
  headerComment?: string;
}

export interface GeneratorResult {
  routesPath?: string;
  importsPath?: string;
  dtsPath?: string;
  routeCount: number;
  layoutCount: number;
}

export const DEFAULT_HEADER_COMMENT =
  '// @generated by @ubean/routing/generator — do not edit manually.\n' +
  '// This file is regenerated on every dev start / build.';

export async function generateRouteFiles(scanResult: ScanResult, options: GeneratorOptions): Promise<GeneratorResult> {
  const gen = new RouteFileGenerator(options);
  return gen.generate(scanResult);
}

export class RouteFileGenerator {
  private readonly opts: Required<Omit<GeneratorOptions, 'getRouteMeta' | 'getImportPath' | 'getLayoutImportPath'>> &
    Pick<GeneratorOptions, 'getRouteMeta' | 'getImportPath' | 'getLayoutImportPath'>;

  constructor(options: GeneratorOptions) {
    const dtsPath = options.dtsPath ?? joinPosix(options.outDir, 'typed-router.d.ts');
    this.opts = {
      cwd: options.cwd,
      srcDir: options.srcDir ?? joinPosix(options.cwd, 'src'),
      outDir: options.outDir,
      dtsPath,
      generateRoutes: options.generateRoutes ?? true,
      generateImports: options.generateImports ?? true,
      generateDts: options.generateDts ?? true,
      routeLazy: options.routeLazy ?? true,
      layoutLazy: options.layoutLazy ?? true,
      headerComment: options.headerComment ?? DEFAULT_HEADER_COMMENT,
      getRouteMeta: options.getRouteMeta,
      getImportPath: options.getImportPath,
      getLayoutImportPath: options.getLayoutImportPath
    } as RouteFileGenerator['opts'];
  }

  async generate(scanResult: ScanResult): Promise<GeneratorResult> {
    const { cwd, outDir, dtsPath, generateRoutes, generateImports, generateDts } = this.opts;

    const routesPath = generateRoutes ? joinPosix(outDir, 'routes.ts') : undefined;
    const importsPath = generateImports ? joinPosix(outDir, 'imports.ts') : undefined;
    const finalDtsPath = generateDts ? dtsPath : undefined;

    await Promise.all([
      routesPath ? writeFile(resolvePath(cwd, routesPath), this.renderRoutesFile(scanResult)) : null,
      importsPath ? writeFile(resolvePath(cwd, importsPath), this.renderImportsFile(scanResult)) : null,
      finalDtsPath ? writeFile(resolvePath(cwd, finalDtsPath), this.renderDtsFile(scanResult)) : null
    ]);

    return {
      routesPath,
      importsPath,
      dtsPath: finalDtsPath,
      routeCount: scanResult.pages.length,
      layoutCount: scanResult.layouts.length
    };
  }

  /* ----------------------------------------------------------------------- */
  /* routes.ts                                                               */
  /* ----------------------------------------------------------------------- */

  renderRoutesFile(scanResult: ScanResult): string {
    const header = this.opts.headerComment;
    const items = scanResult.pages.map(p => this.renderRouteRecord(p)).join(',\n');

    return `${header}

import type { RouteRecord } from './imports';

export const routes: RouteRecord[] = [
${items}
];
`;
  }

  private renderRouteRecord(page: ScannedPageRoute): string {
    const parts: string[] = [];
    parts.push(`    name: ${JSON.stringify(page.name)}`);
    parts.push(`    path: ${JSON.stringify(page.route)}`);

    // `component` is a RouteFileKey — a key into the `views` map in imports.ts.
    // For reuse routes, use the `reuseTarget`'s name so `views[component]`
    // resolves to the target's component loader (the .reuse.ts file only
    // contains metadata, not a Vue component).
    const componentKey = page.isReuse && page.reuseTarget ? page.reuseTarget : page.name;
    parts.push(`    component: ${JSON.stringify(componentKey)}`);

    if (page.layout !== undefined) {
      const layoutVal = page.layout === false ? 'false' : JSON.stringify(page.layout);
      parts.push(`    layout: ${layoutVal}`);
    }

    if (page.isReuse) {
      parts.push(`    reuse: true`);
    }

    const meta = this.computeMeta(page);
    if (meta && Object.keys(meta).length > 0) {
      parts.push(`    meta: ${JSON.stringify(meta)}`);
    }

    if (page.pageMeta?.cache === true) {
      parts.push(`    cache: true`);
    }

    if (page.pageMeta?.requiresAuth === true) {
      parts.push(`    requiresAuth: true`);
    }

    if (page.pageMeta?.middleware) {
      const mw = page.pageMeta.middleware;
      const mwVal = Array.isArray(mw) ? JSON.stringify(mw) : JSON.stringify(mw);
      parts.push(`    middleware: ${mwVal}`);
    }

    return `  {\n${parts.join(',\n')}\n  }`;
  }

  private computeMeta(page: ScannedPageRoute): Record<string, unknown> | null {
    const base = page.pageMeta?.meta ?? {};
    const extra = this.opts.getRouteMeta?.(page) ?? {};

    // Existing keys take precedence (do not overwrite definePage meta)
    const merged: Record<string, unknown> = { ...extra, ...base };
    return Object.keys(merged).length > 0 ? merged : null;
  }

  /* ----------------------------------------------------------------------- */
  /* imports.ts                                                              */
  /* ----------------------------------------------------------------------- */

  renderImportsFile(scanResult: ScanResult): string {
    const header = this.opts.headerComment;
    const layouts = scanResult.layouts.map(l => this.renderLayoutImport(l)).join(',\n');
    const views = scanResult.pages
      .filter(p => !p.isReuse)
      .map(p => this.renderViewImport(p))
      .join(',\n');

    const layoutType =
      scanResult.layouts.length > 0 ? `'${scanResult.layouts.map(l => l.name).join("' | '")}'` : 'string';

    // Categorize route keys following the elegant-router model:
    //   - RouteFileKey:   routes with a real .vue/.md file (excludes reuse & builtin)
    //   - RouteReuseKey:  routes declared via `.reuse.ts` / `.reuse.vue`
    //   - BuiltinRouteKey: framework-provided routes (root / not_found / ...)
    //   - RouteKey:       union of the above (= all page route names)
    const filePages = scanResult.pages.filter(p => !p.isReuse);
    const reusePages = scanResult.pages.filter(p => p.isReuse);

    const fileKeyType = filePages.length > 0 ? `'${filePages.map(p => p.name).join("' | '")}'` : 'never';
    const reuseKeyType = reusePages.length > 0 ? `'${reusePages.map(p => p.name).join("' | '")}'` : 'never';
    const allKeyType = scanResult.pages.length > 0 ? `'${scanResult.pages.map(p => p.name).join("' | '")}'` : 'never';

    return `${header}

export type LayoutKey = ${layoutType};

/**
 * Route keys that have a corresponding source file (\`.vue\` / \`.md\`).
 * Excludes reuse routes and builtin routes.
 *
 * The \`views\` map is keyed by this type — \`views[RouteFileKey]\` resolves
 * to the actual component loader.
 */
export type RouteFileKey = ${fileKeyType};

/**
 * Route keys declared via \`.reuse.ts\` / \`.reuse.vue\`.
 * They reference another route's component via \`reuseTarget\`.
 */
export type RouteReuseKey = ${reuseKeyType};

/**
 * Builtin route keys (framework-provided, e.g. \`root\` / \`not_found\`).
 * Currently unused — reserved for future builtin pages.
 */
export type BuiltinRouteKey = never;

/**
 * All page route names. Union of {@link RouteFileKey}, {@link RouteReuseKey}
 * and {@link BuiltinRouteKey}.
 */
export type RouteKey = ${allKeyType};

export type Lazy<T> = () => Promise<T>;
export type RawRouteComponent = import('vue').Component | Lazy<import('vue').Component>;

export interface RouteRecord {
  name: RouteKey;
  path: string;
  /**
   * Key into the \`views\` map — resolve the actual component via
   * \`views[route.component]\`.
   *
   * For reuse routes, this is the \`reuseTarget\`'s \`RouteFileKey\`
   * (not the reuse route's own name), so the same component is reused.
   */
  component: RouteFileKey;
  layout?: LayoutKey | false;
  reuse?: boolean;
  meta?: Record<string, unknown>;
  cache?: boolean;
  requiresAuth?: boolean;
  middleware?: string | string[];
}

export const layouts: Record<LayoutKey, RawRouteComponent> = {
${layouts}
};

export const views: Record<RouteFileKey, RawRouteComponent> = {
${views}
};
`;
  }

  private renderLayoutImport(layout: ScannedLayout): string {
    const importPath = this.opts.getLayoutImportPath?.(layout) ?? defaultLayoutImportPath(layout, this.opts.srcDir);
    const lazy = typeof this.opts.layoutLazy === 'function' ? this.opts.layoutLazy(layout) : this.opts.layoutLazy;
    if (lazy) {
      return `  ${layout.name}: () => import(${JSON.stringify(importPath)})`;
    }
    const importName = `__layout_${layout.name}`;
    return `  ${layout.name}: ${importName}, // import ${importName} from ${JSON.stringify(importPath)}`;
  }

  private renderViewImport(page: ScannedPageRoute): string {
    const importPath = this.opts.getImportPath?.(page) ?? defaultPageImportPath(page, this.opts.srcDir);
    const lazy = typeof this.opts.routeLazy === 'function' ? this.opts.routeLazy(page) : this.opts.routeLazy;
    if (lazy) {
      return `  ${page.name}: () => import(${JSON.stringify(importPath)})`;
    }
    return `  ${page.name}: ${page.name}, // import ${page.name} from ${JSON.stringify(importPath)}`;
  }

  /* ----------------------------------------------------------------------- */
  /* typed-router.d.ts                                                       */
  /* ----------------------------------------------------------------------- */

  renderDtsFile(scanResult: ScanResult): string {
    const header = this.opts.headerComment;

    const pathMapEntries =
      scanResult.pages.length > 0
        ? scanResult.pages.map(p => `    "${p.name}": "${p.route}";`).join('\n')
        : '    // (no pages scanned)';

    const reuseRoutes = scanResult.pages.filter(p => p.isReuse);
    const reuseKeys = reuseRoutes.length > 0 ? reuseRoutes.map(p => `"${p.name}"`).join(' | ') : 'never';

    const layoutKeyList =
      scanResult.layouts.length > 0 ? scanResult.layouts.map(l => `"${l.name}"`).join(' | ') : 'never';

    // RouteNamedMap:每条路由 → RouteRecordInfo<Name, Path, ParamsRaw, Params>
    // 让 vue-router 的 useRoute<Name>(name) 能推断 route.params 的类型。
    const routeNamedMapEntries =
      scanResult.pages.length > 0
        ? scanResult.pages.map(p => `    "${p.name}": ${this.renderRouteRecordInfo(p)};`).join('\n')
        : '    // (no pages scanned)';

    return `${header}

declare module '@ubean/routing' {
  /**
   * Route layout keys scanned from \`src/layouts/\`.
   */
  export type RouteLayoutKey = ${layoutKeyList};

  /**
   * Map of route name → route path, scanned from \`src/pages/\`.
   */
  export interface RoutePathMap {
${pathMapEntries}
  }

  /**
   * Route names (keys of {@link RoutePathMap}).
   */
  export type RouteKey = keyof RoutePathMap;

  /**
   * Route paths (values of {@link RoutePathMap}).
   */
  export type RoutePath = RoutePathMap[RouteKey];

  /**
   * Reuse route keys (pages using \`.reuse.vue\` suffix).
   */
  export type ReuseRouteKey = ${reuseKeys};

  /**
   * Builtin route keys (framework-provided, e.g. \`root\` / \`not_found\`).
   * Currently unused — reserved for future builtin pages.
   */
  export type BuiltinRouteKey = never;

  /**
   * Route keys that have a corresponding source file (\`.vue\` / \`.md\`).
   * Excludes reuse routes and builtin routes.
   *
   * Use this to index the \`views\` map for component lookup.
   */
  export type RouteFileKey = Exclude<RouteKey, ReuseRouteKey | BuiltinRouteKey>;
}

declare module 'vue-router/auto-routes' {
  import type { RouteRecordInfo, ParamValue, ParamValueZeroOrOne } from 'vue-router';

  /**
   * Route named map — enables typed \`useRoute<Name>(name)\` via vue-router's
   * \`TypesConfig\` augmentation below.
   *
   * Each entry describes a route's name, path, and the types of its path
   * params (raw input vs. resolved value). For routes without params,
   * \`Record<never, never>\` is used.
   *
   * @see https://router.vuejs.org/api/interfaces/RouteRecordInfo.html
   */
  export interface RouteNamedMap {
${routeNamedMapEntries}
  }
}

declare module 'vue-router' {
  export interface TypesConfig {
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap;
  }
}

export type { RouteLayoutKey, RoutePathMap, RouteKey, RoutePath, ReuseRouteKey, BuiltinRouteKey, RouteFileKey } from '@ubean/routing';
`;
  }

  /**
   * 渲染单条路由的 `RouteRecordInfo<Name, Path, ParamsRaw, Params>`。
   *
   * 参数类型映射:
   * - 必需参数(`/users/:id`)    → `{ id: ParamValue<true> }` / `{ id: ParamValue<false> }`
   * - 可选参数(`/users/:id?`)   → `{ id?: ParamValueZeroOrOne<true> }` / `{ id?: ParamValueZeroOrOne<false> }`
   * - 无参数(`/about`)          → `Record<never, never>`
   *
   * `ParamValue<true>` 表示原始输入类型(必需为 string),`ParamValue<false>` 表示
   * 解析后类型(已编码/解码,可能为 `string | undefined`)。这是 vue-router 的约定。
   */
  private renderRouteRecordInfo(page: ScannedPageRoute): string {
    const params = extractRouteParams(page.route);
    const paramsRaw = renderParamsType(params, /* isRaw */ true);
    const paramsResolved = renderParamsType(params, /* isRaw */ false);
    return `RouteRecordInfo<${JSON.stringify(page.name)}, ${JSON.stringify(page.route)}, ${paramsRaw}, ${paramsResolved}>`;
  }
}

/* -------------------------------------------------------------------------- */
/* Helpers                                                                    */
/* -------------------------------------------------------------------------- */

/**
 * Extensions stripped when computing the default import specifier.
 *
 * `.vue` / `.md` / `.mdx` are KEPT — Vite dispatches them to dedicated
 * transforms (vue-loader / markdown) based on the extension, so the
 * explicit suffix is required for correct resolution at runtime.
 *
 * `.ts` / `.tsx` / `.js` / `.jsx` are STRIPPED — TypeScript/Vite convention
 * is to import script modules without their extension.
 */
const STRIPPABLE_IMPORT_EXT = /\.(tsx?|jsx?)$/;

/**
 * Compute the default import specifier for a page.
 *
 * Uses `srcDir` (not `cwd`) as the relative base so that the resulting
 * `@/<rel>` path matches the common `@/` → `src/` path alias. For example,
 * a page at `<cwd>/src/pages/about.vue` becomes `@/pages/about.vue`
 * (NOT `@/src/pages/about.vue`, which would double the `src/` prefix and
 * fail to resolve under the standard alias).
 */
function defaultPageImportPath(page: ScannedPageRoute, srcDir: string): string {
  const rel = relativePosix(srcDir, page.fullPath);
  const importPath = rel.replace(STRIPPABLE_IMPORT_EXT, '');
  return `@/${importPath}`;
}

function defaultLayoutImportPath(layout: ScannedLayout, srcDir: string): string {
  const rel = relativePosix(srcDir, layout.fullPath);
  const importPath = rel.replace(STRIPPABLE_IMPORT_EXT, '');
  return `@/${importPath}`;
}

/**
 * 从 vue-router 风格路径中提取参数信息。
 *
 * 支持的语法:
 * - `:name`     — 必需参数(如 `/users/:id`)
 * - `:name?`    — 可选参数(如 `/users/:id?`)
 * - `:name*`    — 重复参数(零或多个,如 `/files/:path*`)— 当前当作可选处理
 * - `:name+`    — 重复参数(一个或多个,如 `/files/:path+`)— 当前当作必需处理
 * - `:name(...)` — 带自定义正则的参数(如 `:id(\\d+)`)— 提取 `name`,忽略正则
 *
 * 不识别 `:pathMatch(.*)*`(catch-all),由 vue-router 内部处理,在
 * `RouteRecordInfo` 中视为无参数(`Record<never, never>`)。
 *
 * @returns 参数数组,顺序与 path 中出现顺序一致
 */
function extractRouteParams(path: string): Array<{ name: string; optional: boolean }> {
  const params: Array<{ name: string; optional: boolean }> = [];
  // 匹配 `:name` 后跟可选的 `(...)` 正则,以及 `?`/`*`/`+` 修饰符
  const paramRegex = /:([A-Za-z_][A-Za-z0-9_]*)(?:\([^)]*\))?([?*+]?)/g;
  let match: RegExpExecArray | null;
  while ((match = paramRegex.exec(path)) !== null) {
    const name = match[1];
    const modifier = match[2];
    // `?` 和 `*` 表示可选(零个或零/多个),`+` 表示必需(一个或多个),无修饰符表示必需
    const optional = modifier === '?' || modifier === '*';
    // 去重:vue-router 不允许同名参数出现两次
    if (!params.some(p => p.name === name)) {
      params.push({ name, optional });
    }
  }
  return params;
}

/**
 * 渲染参数类型字面量,用于 `RouteRecordInfo` 的 `ParamsRaw` / `Params` 类型参数位置。
 *
 * @param params   `extractRouteParams` 返回的参数数组
 * @param isRaw    `true` 渲染原始输入类型(`ParamValue<true>` / `ParamValueZeroOrOne<true>`),
 *                 `false` 渲染解析后类型(`ParamValue<false>` / `ParamValueZeroOrOne<false>`)
 * @returns 类型字面量字符串,如 `{ id: ParamValue<true> }` 或 `Record<never, never>`
 */
function renderParamsType(params: Array<{ name: string; optional: boolean }>, isRaw: boolean): string {
  if (params.length === 0) {
    return 'Record<never, never>';
  }
  const entries = params.map(p => {
    const optionalMarker = p.optional ? '?' : '';
    const type = p.optional
      ? `ParamValueZeroOrOne<${isRaw ? 'true' : 'false'}>`
      : `ParamValue<${isRaw ? 'true' : 'false'}>`;
    return `    ${p.name}${optionalMarker}: ${type}`;
  });
  return `{\n${entries.join(',\n')}\n  }`;
}

function joinPosix(...parts: string[]): string {
  return parts
    .map(p => p.replace(/\\/g, '/'))
    .join('/')
    .replace(/\/+/g, '/');
}

/**
 * 将 `cwd` 与 `target` 合并为最终写入路径。
 *
 * 与 `joinPosix` 不同,此函数会识别 `target` 是否为绝对路径:
 * - 如果 `target` 以 `/` 开头(POSIX 绝对路径)或盘符开头(Windows,如 `C:`),
 *   直接使用 `target`,忽略 `cwd`
 * - 否则,使用 `joinPosix(cwd, target)` 拼接
 *
 * 这是为了支持消费方(`@ubean/build`)传入 `path.resolve()` 计算出的绝对路径,
 * 避免出现 `<cwd>/<absolute-target>` 这种重复前缀的错误路径(参见
 * `maybeGenerateRouteFiles` 中 `resolve(config.rootDir, ...)` 的调用)。
 */
function resolvePath(cwd: string, target: string): string {
  const normalized = target.replace(/\\/g, '/');
  // POSIX 绝对路径(/...)或 Windows 绝对路径(C:\... / C:/...)
  if (normalized.startsWith('/') || /^[a-zA-Z]:[\\/]/.test(normalized)) {
    return normalized;
  }
  return joinPosix(cwd, normalized);
}

function relativePosix(from: string, to: string): string {
  // Lightweight posix `path.relative` without pulling in `pathe` here.
  const fromParts = resolvePosix(from).split('/').filter(Boolean);
  const toParts = resolvePosix(to).split('/').filter(Boolean);

  let i = 0;
  while (i < fromParts.length && i < toParts.length && fromParts[i] === toParts[i]) i++;

  const up = fromParts.slice(i).map(() => '..');
  const down = toParts.slice(i);
  return [...up, ...down].join('/') || '.';
}

function resolvePosix(p: string): string {
  if (p.startsWith('/')) return p.replace(/\\/g, '/');
  return p.replace(/\\/g, '/');
}

async function writeFile(path: string, content: string): Promise<void> {
  const { mkdir, writeFile: fsWriteFile } = await import('node:fs/promises');
  const { dirname } = await import('node:path');
  await mkdir(dirname(path), { recursive: true });
  await fsWriteFile(path, content, 'utf-8');
}
