// @generated by @ubean/routing/generator — do not edit manually.
// This file is regenerated on every dev start / build.

declare module '@ubean/routing' {
  /**
   * Route layout keys scanned from `src/layouts/`.
   */
  export type RouteLayoutKey = 'default';

  /**
   * Map of route name → route path, scanned from `src/pages/`.
   */
  export interface RoutePathMap {
    About: '/about';
    Index: '/';
    UsersId: '/users/:id';
  }

  /**
   * Route names (keys of {@link RoutePathMap}).
   */
  export type RouteKey = keyof RoutePathMap;

  /**
   * Route paths (values of {@link RoutePathMap}).
   */
  export type RoutePath = RoutePathMap[RouteKey];

  /**
   * Reuse route keys (pages using `.reuse.vue` suffix).
   */
  export type ReuseRouteKey = never;
}

export type { RouteLayoutKey, RoutePathMap, RouteKey, RoutePath, ReuseRouteKey } from '@ubean/routing';
